In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from scipy.stats import linregress
from tqdm import tqdm
import os

In [2]:
import matplotlib as mpl
mpl.rcParams['pdf.fonttype'] = 42
mpl.rcParams['ps.fonttype'] = 42
plt.rc("font",family="Arial")

In [3]:
os.chdir(r"J:\BLA_three_types\terminal_corr")

In [5]:
os.listdir()[0]

['all_terminal_infor_combine.csv']

In [4]:
df = pd.read_csv('all_terminal_infor_combine.csv',index_col =0)

In [5]:
dfc = pd.read_excel(r"J:\BLA_three_types\cluster\BLA_3_cluster5.xlsx")

In [12]:
df = df.loc[df.filename.isin(dfc.file.tolist())]

In [13]:
df.to_csv("all_terminal_infor_combine_new.csv")

In [14]:
df

,ID,type,AP,DV,ML,R,parent,area_ID,area_name,name_use,bratch_ID,side,terminal,soma_AP,soma_DV,soma_ML,filename
88,89,2,7071.76,5539.86,2596.90,0.757812,88,579,ec,ec,5,left,1,7205.00,5497.94,2557.34,221058_038_Sst
163,164,3,7311.68,5540.48,2552.32,0.847656,163,303,BLAa,BLA,8,left,1,7205.00,5497.94,2557.34,221058_038_Sst
208,209,3,7095.62,5518.10,2573.66,0.437500,208,579,ec,ec,9,left,1,7205.00,5497.94,2557.34,221058_038_Sst
251,252,3,7159.82,5461.50,2497.44,0.003906,251,303,BLAa,BLA,10,left,1,7205.00,5497.94,2557.34,221058_038_Sst
375,376,3,7221.38,5531.48,2504.80,0.351562,375,303,BLAa,BLA,21,left,1,7205.00,5497.94,2557.34,221058_038_Sst
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26220,26221,2,2543.98,2906.74,5615.78,1.000000,26220,171,PL1,PL,207,left,1,6454.62,5418.40,2393.60,251039_033_Vglut1
26276,26277,2,2654.52,2849.58,5657.60,0.667969,26276,171,PL1,PL,208,left,1,6454.62,5418.40,2393.60,251039_033_Vglut1
26332,26333,2,2144.28,3012.56,5615.16,1.000000,26332,484,ORBm1,ORB,210,left,1,6454.62,5418.40,2393.60,251039_033_Vglut1
26354,26355,2,2106.56,2966.36,5594.00,1.000000,26354,484,ORBm1,ORB,211,left,1,6454.62,5418.40,2393.60,251039_033_Vglut1
26433,26434,2,2068.92,2905.60,5561.08,0.917969,26433,484,ORBm1,ORB,212,left,1,6454.62,5418.40,2393.60,251039_033_Vglut1

In [40]:
"MO" in df.name_use.unique()

True

In [15]:
color_dict = {"Vglut1":'#107010',"Sst":'#0000ff',"Crh":'red'}

In [ ]:
# Extended Data Fig7a
for name_use in [["PL","ORB","ACA","ILA","FRP"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = "PFC2"
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [28]:
# Extended Data Fig7a
for name_use in [["MO","MOp","SS","SSp"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = "sensory"
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [16]:
# Extended Data Fig7a
for name_use in [["PB"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = "PB"
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [17]:
# Extended Data Fig7a
for name_use in [["SI"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [18]:
# Extended Data Fig7a
for name_use in [["BST"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [29]:
# Extended Data Fig7a
for name_use in [["MO"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [30]:
# Extended Data Fig7a
for name_use in [["PL"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [31]:
# Extended Data Fig7a
for name_use in [["ORB"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [29]:
# Extended Data Fig7a
for name_use in [["ACA"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [31]:
# Extended Data Fig7a
for name_use in [["AI"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [19]:
# Extended Data Fig7a
for name_use in [["AON"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [20]:
# Extended Data Fig7a
for name_use in [["CP"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [21]:
# Extended Data Fig7a
for name_use in [["ACB"]]:
        dfplot = df.loc[(df.name_use.isin(name_use))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","AP","DV","ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["AP","DV","ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3f}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        name_uses = name_use[0]
        plt.suptitle('BLA_%s_all'%name_uses, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("BLA_%s_all.jpg"%name_uses,dpi=600)
        plt.savefig("BLA_%s_all.pdf"%name_uses,dpi=600)
        dfplot.to_csv("BLA_all_plot1_%s.csv"%name_uses)
        dfplot2.to_csv("BLA_all_plot2_%s.csv"%name_uses)
        plt.close()

In [6]:
dfall = pd.read_csv("terminal_info_type2&4&22.csv",index_col=0)
df = dfall.loc[dfall.type == 22]

C:\Users\zljia\AppData\Local\Temp\ipykernel_25712\817049525.py:1: DtypeWarning: Columns (12,13,19) have mixed types. Specify dtype option on import or set low_memory=False.
  dfall = pd.read_csv("terminal_info_type2&4&22.csv",index_col=0)

In [7]:
df

,id,ter_AP,ter_DV,ter_ML,radius,parent,region,neuron,soma_AP,soma_DV,soma_ML,somas_hemisphere,terminal_hemisphere,is_ipsi,filename,type,somas,geno,region_new
index,,,,,,,,,,,,,,,,,,,
0.0,2836.0,8060.67,5939.54,4884.86,0.351562,2835,SUM,210996_013,7998.15,5927.49,4909.54,True,True,True,210996_013_Adcyap1_SUM,22.0,MBO,Adcyap1,MBO
1.0,2941.0,8092.97,5935.99,4853.64,0.875000,2940,MB,210996_013,7998.15,5927.49,4909.54,True,True,True,210996_013_Adcyap1_SUM,22.0,MBO,Adcyap1,MB
2.0,4052.0,8138.30,5992.15,4867.93,0.292969,4051,MB,210996_013,7998.15,5927.49,4909.54,True,True,True,210996_013_Adcyap1_SUM,22.0,MBO,Adcyap1,MB
3.0,4135.0,8167.15,5926.21,4882.24,0.351562,4134,MB,210996_013,7998.15,5927.49,4909.54,True,True,True,210996_013_Adcyap1_SUM,22.0,MBO,Adcyap1,MB
4.0,4147.0,8065.55,5978.83,4866.02,0.554688,4146,SUM,210996_013,7998.15,5927.49,4909.54,True,True,True,210996_013_Adcyap1_SUM,22.0,MBO,Adcyap1,MBO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6.0,2973.0,8217.54,5961.40,4883.53,0.523438,2972,MB,211269_106,8076.63,6132.66,4854.36,True,True,True,211269_106_Tac2_LM,22.0,MBO,Tac2,MB
7.0,2993.0,8230.14,5944.69,4924.16,0.351562,2992,root,211269_106,8076.63,6132.66,4854.36,True,True,True,211269_106_Tac2_LM,22.0,MBO,Tac2,root
8.0,3072.0,7900.22,6203.17,4553.02,0.437500,3071,LM,211269_106,8076.63,6132.66,4854.36,True,True,True,211269_106_Tac2_LM,22.0,MBO,Tac2,MBO
9.0,3117.0,7884.51,6116.18,4723.08,0.730469,3116,LM,211269_106,8076.63,6132.66,4854.36,True,True,True,211269_106_Tac2_LM,22.0,MBO,Tac2,MBO
10.0,3150.0,6380.48,4853.97,5140.61,1.371094,3149,mtt,211269_106,8076.63,6132.66,4854.36,True,True,True,211269_106_Tac2_LM,22.0,MBO,Tac2,mtt

In [8]:
color_dict = {'Adcyap1': '#ff0000', 'Tac2': '#00ffff', 'Nts': '#000080','Pdyn': '#93278f'}

In [11]:
# Extended Data Fig7a
for region in [["AMd","AMv","AD","AV","IAM","IAD","LD"]]:
        dfplot = df.loc[(df.region.isin(region))]
        dfplot2 = dfplot.pivot_table(index="filename",values=["soma_AP","soma_DV","soma_ML","ter_AP","ter_DV","ter_ML"],aggfunc="mean")
        dfplot2["color"] = [color_dict[item.split("_")[2]] for item in dfplot2.index.to_list()]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["ter_AP","ter_DV","ter_ML"]):
                        x = dfplot2[soma_label]
                        y = dfplot2[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot2["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3e}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot2)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        regions = "ATN"
        plt.suptitle('type22_%s_all'%regions, fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("type22_%s_all.jpg"%regions,dpi=600)
        plt.savefig("type22_%s_all.pdf"%regions,dpi=600)
        dfplot.to_csv("type22_all_plot1_%s.csv"%regions)
        dfplot2.to_csv("type22_all_plot2_%s.csv"%regions)
        plt.close()

In [13]:
# Extended Data Fig11c
for geno in ["Tac2","Nts"]:
        dfplot_tmp = dfplot2.loc[dfplot2.index.str.contains(geno)]
        fig, axs = plt.subplots(3, 3, figsize=(15, 12))
        for i,soma_label in enumerate(["soma_AP","soma_DV","soma_ML"]):
                for j,ter_label in enumerate(["ter_AP","ter_DV","ter_ML"]):
                        x = dfplot_tmp[soma_label]
                        y = dfplot_tmp[ter_label]

                        regression_result = linregress(x, y)
                        axs[i, j].scatter(x=x, y=y, s=10,c= dfplot_tmp["color"])
                        axs[i, j].plot([min(x), max(x)],
                                [min(x) * regression_result.slope + regression_result.intercept,
                                max(x) * regression_result.slope + regression_result.intercept],
                                c='black',
                                linewidth=1.5,
                                dashes=[4, 2]
                                )
                        textstr = '\n'.join(['r = {:.3f}'.format(regression_result.rvalue),
                                'p = {:.3e}'.format(regression_result.pvalue),
                                "n = %d"%len(dfplot_tmp)])
                        axs[i, j].text(x = 0.02,
                                y = 0.9,   
                                s = textstr,
                                transform=axs[i, j].transAxes, 
                                fontsize=12,
                                verticalalignment='top'
                                )

                        if soma_label.__contains__("ML"):
                                axs[i, j].invert_xaxis()

                        if ter_label.__contains__("ML"):
                                axs[i, j].invert_yaxis()


                        axs[i, j].set_title(soma_label+"-"+ter_label)
                        axs[i, j].set_xlabel(soma_label)
                        axs[i, j].set_ylabel(ter_label)
        regions = "ATN"
        plt.suptitle('type22_%s_%s'%(regions,geno), fontsize=16, fontweight='bold')
        plt.subplots_adjust(wspace=0.25, hspace=0.35) 
        plt.savefig("type22_%s_%s.jpg"%(regions,geno),dpi=600)
        plt.savefig("type22_%s_%s.pdf"%(regions,geno),dpi=600)
        plt.close()