In [2]:
import os
import pandas as pd

In [14]:
os.chdir(r"J:\BLA_three_types\bilateral")

In [15]:
os.listdir()

['projection_length_contra.csv',
 'projection_length_contra_combine.xlsx',
 'projection_length_ipsi_combine.xlsx',
 'projection_length_ipsi.csv',
 'BLA_neurons_bilateral_all.xlsx',
 'bilateral_top100.csv',
 'morphology_matrix.csv',
 'morphology_matrix39.csv',
 'BLA_3_plot_70.csv',
 'BLA_geno_location2.csv',
 'heatmap',
 'heatmap - 副本',
 'bilateral_top66.csv',
 'df_tmp.csv']

In [16]:
df_contra = pd.read_excel(r"projection_length_contra_combine.xlsx",index_col=0)
df_contra = df_contra.loc[:, (df_contra != 0).any(axis=0)]
df_contra.columns = [item+"_contra" for item in df_contra.columns.tolist()]

In [17]:
df_ipsi = pd.read_excel(r"projection_length_ipsi_combine.xlsx",index_col=0)
df_ipsi = df_ipsi.loc[:, (df_ipsi != 0).any(axis=0)]
df_ipsi.columns = [item+"_ipsi" for item in df_ipsi.columns.tolist()]

In [40]:
dfdata = pd.concat([df_ipsi,df_contra],axis =1)

In [7]:
dfdata

,int_ipsi,PSV_ipsi,PT_ipsi,AAA_ipsi,ACB_ipsi,ADP_ipsi,VL_ipsi,nst_ipsi,och_ipsi,opt_ipsi,...,ENT_contra,GU_contra,AI_contra,BLA_contra,MOp_contra,PERI_contra,MOs_contra,SSs_contra,VISC_contra,EP_contra
251034_010_Vglut1,0.000000,0.0,0.0,0.000000,12177.902425,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234172_015_Crh,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234065_020_Pkc,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
221058_038_Sst,2880.183789,0.0,0.0,0.000000,75.257641,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234065_009_Pkc,0.000000,0.0,0.0,577.353016,269.019952,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234065_015_Pkc,0.000000,0.0,0.0,671.423875,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
242657_002_Pkc,0.000000,0.0,0.0,554.960436,902.733458,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
242658_044_Pkc,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234065_016_Pkc,0.000000,0.0,0.0,542.604428,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
242657_038_Pkc,0.000000,0.0,0.0,1250.704867,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
dfdata = pd.read_csv("all_terminal_infor_table_axon_intensity_top60.csv",sep = ",",index_col=0)

In [ ]:
dfdata = pd.read_csv("terminal_intensity_top60.csv",index_col=0)

In [8]:
dfdata.to_excel("BLA_neurons_bilateral_all.xlsx")

In [41]:
dfdata = dfdata.loc[~dfdata.index.str.contains("Pkc")]

In [46]:
dfdata.loc["sum"] =dfdata.apply(lambda x:x.sum(),axis =0)
dfdata = dfdata.sort_values(by = "sum",axis=1,ascending=False)
dfdata2 = dfdata.iloc[:,0:100]
df50  =dfdata2.drop(labels='sum',axis=0) 
# df50.to_csv("bilateral_top100.csv")
# df50.to_excel("POA_top50.xlsx")

In [ ]:
area_list = ['CEA_ipsi', 'BLA_ipsi', 'CP_ipsi', 'SI_ipsi', 'OT_ipsi', 'ACB_ipsi', 'PL_ipsi', 'BMA_ipsi', 'ORB_ipsi', 'IA_ipsi', 'CP_contra', 'PB_ipsi', 'EP_ipsi', 'AAA_ipsi', 'ACA_ipsi', 'BST_ipsi', 'OT_contra', 'PIR_ipsi', 'MY_ipsi', 'LA_ipsi', 'MO_ipsi', 'COA_ipsi', 'AON_ipsi', 'AI_ipsi', 'CA1_ipsi', 'MEA_ipsi', 'ILA_ipsi', 'PPN_ipsi', 'GPe_ipsi', 'TR_ipsi', 'ENT_ipsi', 'FRP_ipsi', 'FS_ipsi', 'SS_contra', 'SNr_ipsi', 'LHA_ipsi', 'MRN_ipsi', 'TT_ipsi', 'ECT_ipsi', 'PA_ipsi', 'LPO_ipsi', 'ACB_contra', 'MA_ipsi', 'SI_contra', 'PAA_ipsi', 'P_ipsi', 'EP_contra', 'ENT_contra', 'ProS_ipsi', 'CENT2_ipsi', 'SS_ipsi', 'V_ipsi', 'TEa_ipsi', 'MO_contra', 'FS_contra', 'SNc_ipsi', 'PIR_contra', 'CENT2_contra', 'PVT_ipsi', 'SUT_ipsi', 'CLA_ipsi', 'ZI_ipsi', 'KF_ipsi', 'STN_ipsi', 'sctv_ipsi', 'CLA_contra', 'PS_ipsi', 'VISC_ipsi', 'AUD_ipsi', 'CUN_ipsi', 'DP_ipsi', 'MPO_ipsi']

In [109]:
area_list2 = ['CEA_ipsi', 'BLA_ipsi', 'CP_ipsi', 'SI_ipsi', 'OT_ipsi', 'ACB_ipsi', 
'PL_ipsi', 'BMA_ipsi', 'ORB_ipsi', 'IA_ipsi', 'CP_contra', 'PB_ipsi', 'EP_ipsi', 
'AAA_ipsi', 'ACA_ipsi', 'BST_ipsi', 'OT_contra', 'PIR_ipsi', 'MY_ipsi', 'LA_ipsi',
 'MO_ipsi', 'COA_ipsi', 'AON_ipsi', 'AI_ipsi', 'CA1_ipsi', 'MEA_ipsi', 'ILA_ipsi',
  'PPN_ipsi', 'GPe_ipsi', 'TR_ipsi', 'ENT_ipsi', 'FRP_ipsi', 'FS_ipsi', 'SS_contra', 
  'SNr_ipsi', 'LHA_ipsi', 'MRN_ipsi', 'TT_ipsi', 'ECT_ipsi', 'PA_ipsi', 'LPO_ipsi', 
  'ACB_contra', 'MA_ipsi', 'SI_contra', 'PAA_ipsi', 'EP_contra', 'ENT_contra', 
  'ProS_ipsi',  'SS_ipsi', 'V_ipsi', 'TEa_ipsi', 'MO_contra', 'FS_contra',
   'SNc_ipsi', 'PIR_contra', 'SUT_ipsi', 'CLA_ipsi',
    'ZI_ipsi', 'STN_ipsi', 'CLA_contra', ]

In [43]:
area_list2 = ['CP_ipsi','BLA_ipsi','OT_ipsi','CEA_ipsi','ACB_ipsi','PL_ipsi','ORB_ipsi','CP_contra','PB_ipsi','EP_ipsi','BMA_ipsi','ACA_ipsi','SI_ipsi',
 'OT_contra','PIR_ipsi','LA_ipsi','MOs_ipsi','COA_ipsi','AON_ipsi','AI_ipsi','CA1_ipsi','ILA_ipsi','IA_ipsi','PPN_ipsi','AAA_ipsi',
 'TR_ipsi','BST_ipsi','ENT_ipsi','FRP_ipsi','GPe_ipsi','SNr_ipsi','MEA_ipsi','FS_ipsi','TT_ipsi','MRN_ipsi','NTS_ipsi','ECT_ipsi',
 'PA_ipsi','PAA_ipsi','PARN_ipsi','ProS_ipsi','V_ipsi','TEa_ipsi','MA_ipsi','MDRN_ipsi','DMX_ipsi',
 'SSs_ipsi','SUT_ipsi','CLA_ipsi','VISC_ipsi','VII_ipsi','AUD_ipsi','CUN_ipsi','PGRN_ipsi','DP_ipsi',
 'ACB_contra','FS_contra','SI_contra','EP_contra','CLA_contra','PIR_contra','SSp_contra','SSs_contra','MOp_contra','ENT_contra',]

In [29]:
"DMX_ipsi" in area_list2

True

In [55]:
df50 = dfdata[area_list2]

In [56]:
df50

,CP_ipsi,BLA_ipsi,OT_ipsi,CEA_ipsi,ACB_ipsi,PL_ipsi,ORB_ipsi,CP_contra,PB_ipsi,EP_ipsi,...,ACB_contra,FS_contra,SI_contra,EP_contra,CLA_contra,PIR_contra,SSp_contra,SSs_contra,MOp_contra,ENT_contra
251034_010_Vglut1,18477.969476,2288.150423,31361.328165,182.021610,12177.902425,11843.636658,16751.794630,0.000000,0.000000,1444.428274,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_015_Crh,0.000000,2970.330035,0.000000,134.399439,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_038_Sst,1156.533573,8255.673888,0.000000,5631.989116,75.257641,0.000000,0.000000,0.000000,5467.253998,7252.425019,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_107_Sst,185.806600,1305.298786,0.000000,2575.047818,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221297_038_Sst,0.000000,564.144862,0.000000,7235.200416,0.000000,0.000000,0.000000,0.000000,11327.702579,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_031_Crh,0.000000,1856.231616,0.000000,2558.780676,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
252460_132_Sst,279.598242,8735.203563,0.000000,3087.389263,0.000000,0.000000,0.000000,0.000000,0.000000,992.656865,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_040_Sst,0.000000,15588.335166,0.000000,1381.652315,0.000000,0.000000,0.000000,0.000000,0.000000,5073.395451,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_016_Crh,0.000000,782.442014,0.000000,2146.379091,0.000000,0.000000,0.000000,0.000000,1026.462770,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
242655_057_Sst,5292.360722,3996.624909,0.000000,4629.639530,0.000000,0.000000,0.000000,0.000000,0.000000,1285.604546,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_017_Crh,6.776553,50.191797,0.000000,3612.722980,0.000000,0.000000,0.000000,0.000000,1424.404948,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_029_Vglut1,85563.939694,3009.669385,3511.218350,560.420377,3485.504156,29878.098182,17792.516772,0.000000,0.000000,2825.222944,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
230058_076_Sst,284.488541,6610.830050,0.000000,2437.856742,0.000000,0.000000,0.000000,0.000000,5316.098383,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
230058_078_Sst,0.000000,5292.527840,0.000000,4054.719217,0.000000,0.000000,0.000000,0.000000,8301.003362,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
252459_079_Sst,2523.105839,2690.807117,0.000000,3470.165044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
230058_074_Sst,0.000000,4446.634763,0.000000,4620.588335,0.000000,0.000000,0.000000,0.000000,13723.567119,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_021_Vglut1,3423.577561,19157.091944,16652.079926,4729.191002,29715.687301,6954.055235,8660.732991,0.000000,0.000000,1982.096366,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251034_001_Vglut1,2832.562245,407.262239,0.000000,0.000000,0.000000,1333.020882,8107.498500,0.000000,0.000000,4360.407417,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_020_Crh,0.000000,512.760546,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_071_Sst,0.000000,16180.973792,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6708.576230,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221297_036_Sst,0.000000,3586.443858,0.000000,8461.117388,0.000000,0.000000,0.000000,0.000000,4692.066585,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_104_Sst,0.000000,538.951414,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
252459_074_Sst,0.000000,1361.005486,0.000000,4475.543910,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_019_Crh,0.000000,1414.245227,0.000000,5033.548617,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221297_037_Sst,0.000000,5416.609052,0.000000,7443.871373,0.000000,0.000000,0.000000,0.000000,8535.301463,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
230058_073_Sst,424.452110,3671.834270,0.000000,3964.387854,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_122_Crh,0.000000,2497.957665,0.000000,12455.045118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_086_Crh,0.000000,2195.030484,0.000000,7459.509776,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_020_Vglut1,13241.743589,18293.513050,0.000000,202.300588,24251.948919,35015.173905,20443.421948,0.000000,0.000000,832.963450,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_033_Vglut1,1964.924881,9988.940591,989.631869,305.247710,0.000000,9766.612592,9984.737784,0.000000,0.000000,5772.010072,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_021_Crh,0.000000,3097.680155,0.000000,2402.307909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_088_Sst,0.000000,3382.488350,0.000000,459.928514,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_031_Vglut1,45732.837545,1312.766809,0.000000,0.000000,2729.331923,0.000000,0.000000,44563.517432,0.000000,8366.640757,...,1092.286950,1621.209588,355.115670,3065.887096,487.144274,0.000000,8616.857046,2795.464027,2559.91932,0.000000
221058_113_Sst,0.000000,20750.510421,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,164.086505,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251034_003_Vglut1,6368.725433,6740.504038,43749.397999,629.587737,17372.033400,8909.356375,9835.244075,18338.850338,0.000000,6274.965722,...,5038.139710,824.234013,5563.895841,2346.218196,1179.352044,2438.062616,0.000000,235.324882,0.00000,4407.917560
251034_004_Vglut1,70356.336579,3883.819883,22482.225571,1034.084054,147.075428,0.000000,799.162656,0.000000,0.000000,2505.711749,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_034_Crh,0.000000,5973.432603,0.000000,3318.236579,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_022_Vglut1,1099.173629,6698.274418,16319.485966,8314.918935,23742.288239,0.000000,0.000000,0.000000,0.000000,2169.777685,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_042_Sst,0.000000,1.241491,0.000000,1899.077710,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
sum,518429.825622,411012.867998,270130.735692,241813.753491,227394.058864,207399.907656,184750.218711,125804.735540,119627.722412,116021.938105,...,12260.853319,4890.887202,11838.023022,10824.210585,3332.992637,4876.125232,17233.714091,6061.577817,5119.83864,8815.835119

In [57]:
df50.to_csv("bilateral_top65.csv")

In [ ]:
df50 = pd.read_csv("bilateral_top65.csv",index_col=0)

In [49]:
df50

,CP_ipsi,BLA_ipsi,OT_ipsi,CEA_ipsi,ACB_ipsi,PL_ipsi,ORB_ipsi,CP_contra,PB_ipsi,EP_ipsi,...,MY_ipsi,VISC_ipsi,ccb_ipsi,LPO_ipsi,VII_ipsi,AUD_ipsi,CUN_ipsi,PGRN_ipsi,DP_ipsi,ee_ipsi
251034_010_Vglut1,18477.969476,2288.150423,31361.328165,182.021610,12177.902425,11843.636658,16751.794630,0.000000,0.000000,1444.428274,...,0.000000,0.000000,576.373514,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_015_Crh,0.000000,2970.330035,0.000000,134.399439,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221058_038_Sst,1156.533573,8255.673888,0.000000,5631.989116,75.257641,0.000000,0.000000,0.000000,5467.253998,7252.425019,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221058_107_Sst,185.806600,1305.298786,0.000000,2575.047818,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,356.505556,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221297_038_Sst,0.000000,564.144862,0.000000,7235.200416,0.000000,0.000000,0.000000,0.000000,11327.702579,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,316.351076,0.000000,0.000000,0.000000
234172_031_Crh,0.000000,1856.231616,0.000000,2558.780676,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
252460_132_Sst,279.598242,8735.203563,0.000000,3087.389263,0.000000,0.000000,0.000000,0.000000,0.000000,992.656865,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,200.085349
221058_040_Sst,0.000000,15588.335166,0.000000,1381.652315,0.000000,0.000000,0.000000,0.000000,0.000000,5073.395451,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,477.066160
234172_016_Crh,0.000000,782.442014,0.000000,2146.379091,0.000000,0.000000,0.000000,0.000000,1026.462770,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
242655_057_Sst,5292.360722,3996.624909,0.000000,4629.639530,0.000000,0.000000,0.000000,0.000000,0.000000,1285.604546,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_017_Crh,6.776553,50.191797,0.000000,3612.722980,0.000000,0.000000,0.000000,0.000000,1424.404948,0.000000,...,179.222202,0.000000,0.000000,0.000000,567.742407,0.000000,0.000000,0.000000,0.000000,0.000000
251039_029_Vglut1,85563.939694,3009.669385,3511.218350,560.420377,3485.504156,29878.098182,17792.516772,0.000000,0.000000,2825.222944,...,0.000000,0.000000,515.618313,0.000000,0.000000,752.182567,0.000000,0.000000,0.000000,0.000000
230058_076_Sst,284.488541,6610.830050,0.000000,2437.856742,0.000000,0.000000,0.000000,0.000000,5316.098383,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
230058_078_Sst,0.000000,5292.527840,0.000000,4054.719217,0.000000,0.000000,0.000000,0.000000,8301.003362,0.000000,...,112.405692,0.000000,0.000000,0.000000,933.874426,0.000000,527.265829,1419.166893,0.000000,0.000000
252459_079_Sst,2523.105839,2690.807117,0.000000,3470.165044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
230058_074_Sst,0.000000,4446.634763,0.000000,4620.588335,0.000000,0.000000,0.000000,0.000000,13723.567119,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,559.848328,0.000000,0.000000,0.000000
251039_021_Vglut1,3423.577561,19157.091944,16652.079926,4729.191002,29715.687301,6954.055235,8660.732991,0.000000,0.000000,1982.096366,...,0.000000,911.685324,0.000000,0.000000,0.000000,748.657473,0.000000,0.000000,402.632527,0.000000
251034_001_Vglut1,2832.562245,407.262239,0.000000,0.000000,0.000000,1333.020882,8107.498500,0.000000,0.000000,4360.407417,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_020_Crh,0.000000,512.760546,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221058_071_Sst,0.000000,16180.973792,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6708.576230,...,0.000000,586.447033,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,657.989133
221297_036_Sst,0.000000,3586.443858,0.000000,8461.117388,0.000000,0.000000,0.000000,0.000000,4692.066585,0.000000,...,717.350684,0.000000,0.000000,0.000000,0.000000,0.000000,71.552782,0.000000,0.000000,0.000000
221058_104_Sst,0.000000,538.951414,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
252459_074_Sst,0.000000,1361.005486,0.000000,4475.543910,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_019_Crh,0.000000,1414.245227,0.000000,5033.548617,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221297_037_Sst,0.000000,5416.609052,0.000000,7443.871373,0.000000,0.000000,0.000000,0.000000,8535.301463,0.000000,...,635.433206,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
230058_073_Sst,424.452110,3671.834270,0.000000,3964.387854,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_122_Crh,0.000000,2497.957665,0.000000,12455.045118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_086_Crh,0.000000,2195.030484,0.000000,7459.509776,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
251039_020_Vglut1,13241.743589,18293.513050,0.000000,202.300588,24251.948919,35015.173905,20443.421948,0.000000,0.000000,832.963450,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,585.938978,0.000000
251039_033_Vglut1,1964.924881,9988.940591,989.631869,305.247710,0.000000,9766.612592,9984.737784,0.000000,0.000000,5772.010072,...,0.000000,131.674341,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,294.634186,0.000000
234172_021_Crh,0.000000,3097.680155,0.000000,2402.307909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221058_088_Sst,0.000000,3382.488350,0.000000,459.928514,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
251039_031_Vglut1,45732.837545,1312.766809,0.000000,0.000000,2729.331923,0.000000,0.000000,44563.517432,0.000000,8366.640757,...,0.000000,0.000000,477.043055,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221058_113_Sst,0.000000,20750.510421,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,164.086505,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
251034_003_Vglut1,6368.725433,6740.504038,43749.397999,629.587737,17372.033400,8909.356375,9835.244075,18338.850338,0.000000,6274.965722,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,66.782176,0.000000
251034_004_Vglut1,70356.336579,3883.819883,22482.225571,1034.084054,147.075428,0.000000,799.162656,0.000000,0.000000,2505.711749,...,0.000000,0.000000,45.866707,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_034_Crh,0.000000,5973.432603,0.000000,3318.236579,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
251039_022_Vglut1,1099.173629,6698.274418,16319.485966,8314.918935,23742.288239,0.000000,0.000000,0.000000,0.000000,2169.777685,...,0.000000,0.000000,0.000000,1213.840588,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221058_042_Sst,0.000000,1.241491,0.000000,1899.077710,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [7]:
dfdata = df50

In [ ]:
dfmatrix = pd.read_csv("morphology_matrix.csv",index_col =0)
dfmatrix39 = dfmatrix.loc[df50.index.tolist()].T.loc[df50.index.tolist()]
dfmatrix39.to_csv("morphology_matrix39.csv")

In [10]:
dfregion = pd.read_excel(r"D:\python\BLA_analysis\brain_areas_HIP.xlsx",index_col=0)

In [ ]:
dfregion = pd.read_excel(r"H:\20220210_figs\brain_areas_for_cortex.xlsx",index_col=0)

In [ ]:
dfregion = pd.read_excel(r"H:\20220210_figs\brain_areas_for_HIP.xlsx",index_col=0)

In [ ]:
dfdata

In [ ]:
df[]

,CEA_ipsi,BLA_ipsi,CP_ipsi,SI_ipsi,OT_ipsi,ACB_ipsi,PL_ipsi,BMA_ipsi,ORB_ipsi,IA_ipsi,...,KF_ipsi,STN_ipsi,sctv_ipsi,CLA_contra,PS_ipsi,VISC_ipsi,AUD_ipsi,CUN_ipsi,DP_ipsi,MPO_ipsi
251034_010_Vglut1,182.02161,2288.150423,18477.969476,4183.218033,31361.328165,12177.902425,11843.636658,0.0,16751.79463,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234172_015_Crh,134.399439,2970.330035,0.0,0.0,0.0,0.0,0.0,0.0,0.0,568.80216,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234065_020_Pkc,1845.727861,2217.44332,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
221058_038_Sst,5631.989116,8255.673888,1156.533573,3576.375407,0.0,75.257641,0.0,111.493625,0.0,365.854078,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234065_009_Pkc,4193.575312,2924.121064,0.0,4609.224952,0.0,269.019952,0.0,692.110508,0.0,641.171221,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242657_002_Pkc,15535.340937,3575.094118,0.0,7282.834435,0.0,902.733458,0.0,585.099589,0.0,417.082362,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
242658_044_Pkc,1247.44831,4322.818749,0.0,0.0,0.0,0.0,0.0,253.414019,0.0,1018.926566,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234065_016_Pkc,10456.780353,7294.394644,0.0,329.831975,0.0,0.0,0.0,1472.941999,0.0,2206.463492,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
242657_038_Pkc,5595.87831,2064.018961,0.0,1595.109521,0.0,0.0,0.0,220.863619,0.0,1577.53755,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
group1,ipsi_STR,ipsi_CTXsp,ipsi_STR,ipsi_PAL,ipsi_STR,ipsi_STR,ipsi_CTX,ipsi_CTXsp,ipsi_CTX,ipsi_STR,...,ipsi_P,ipsi_HY,ipsi_fiber tracts,contra_CTXsp,ipsi_HY,ipsi_CTX,ipsi_CTX,ipsi_MB,ipsi_OLF,ipsi_HY

In [60]:
df = df50

In [ ]:
# contra_all
df.loc["group1",:] = "" 
def get_the_group(x):
    area = dfregion.loc[dfregion["region"] == x.name.split("_")[0]].group.tolist()[0]
    side = x.name.split("_")[1]
    return side+"_"+area
    # return area
df.loc["group1",:] = df.apply(get_the_group, axis=0)

In [59]:
df50

,CP_ipsi,BLA_ipsi,OT_ipsi,CEA_ipsi,ACB_ipsi,PL_ipsi,ORB_ipsi,CP_contra,PB_ipsi,EP_ipsi,...,ACB_contra,FS_contra,SI_contra,EP_contra,CLA_contra,PIR_contra,SSp_contra,SSs_contra,MOp_contra,ENT_contra
251034_010_Vglut1,18477.969476,2288.150423,31361.328165,182.021610,12177.902425,11843.636658,16751.794630,0.000000,0.000000,1444.428274,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_015_Crh,0.000000,2970.330035,0.000000,134.399439,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_038_Sst,1156.533573,8255.673888,0.000000,5631.989116,75.257641,0.000000,0.000000,0.000000,5467.253998,7252.425019,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_107_Sst,185.806600,1305.298786,0.000000,2575.047818,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221297_038_Sst,0.000000,564.144862,0.000000,7235.200416,0.000000,0.000000,0.000000,0.000000,11327.702579,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_031_Crh,0.000000,1856.231616,0.000000,2558.780676,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
252460_132_Sst,279.598242,8735.203563,0.000000,3087.389263,0.000000,0.000000,0.000000,0.000000,0.000000,992.656865,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_040_Sst,0.000000,15588.335166,0.000000,1381.652315,0.000000,0.000000,0.000000,0.000000,0.000000,5073.395451,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_016_Crh,0.000000,782.442014,0.000000,2146.379091,0.000000,0.000000,0.000000,0.000000,1026.462770,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
242655_057_Sst,5292.360722,3996.624909,0.000000,4629.639530,0.000000,0.000000,0.000000,0.000000,0.000000,1285.604546,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_017_Crh,6.776553,50.191797,0.000000,3612.722980,0.000000,0.000000,0.000000,0.000000,1424.404948,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_029_Vglut1,85563.939694,3009.669385,3511.218350,560.420377,3485.504156,29878.098182,17792.516772,0.000000,0.000000,2825.222944,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
230058_076_Sst,284.488541,6610.830050,0.000000,2437.856742,0.000000,0.000000,0.000000,0.000000,5316.098383,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
230058_078_Sst,0.000000,5292.527840,0.000000,4054.719217,0.000000,0.000000,0.000000,0.000000,8301.003362,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
252459_079_Sst,2523.105839,2690.807117,0.000000,3470.165044,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
230058_074_Sst,0.000000,4446.634763,0.000000,4620.588335,0.000000,0.000000,0.000000,0.000000,13723.567119,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_021_Vglut1,3423.577561,19157.091944,16652.079926,4729.191002,29715.687301,6954.055235,8660.732991,0.000000,0.000000,1982.096366,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251034_001_Vglut1,2832.562245,407.262239,0.000000,0.000000,0.000000,1333.020882,8107.498500,0.000000,0.000000,4360.407417,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_020_Crh,0.000000,512.760546,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_071_Sst,0.000000,16180.973792,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6708.576230,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221297_036_Sst,0.000000,3586.443858,0.000000,8461.117388,0.000000,0.000000,0.000000,0.000000,4692.066585,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_104_Sst,0.000000,538.951414,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
252459_074_Sst,0.000000,1361.005486,0.000000,4475.543910,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_019_Crh,0.000000,1414.245227,0.000000,5033.548617,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221297_037_Sst,0.000000,5416.609052,0.000000,7443.871373,0.000000,0.000000,0.000000,0.000000,8535.301463,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
230058_073_Sst,424.452110,3671.834270,0.000000,3964.387854,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_122_Crh,0.000000,2497.957665,0.000000,12455.045118,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_086_Crh,0.000000,2195.030484,0.000000,7459.509776,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_020_Vglut1,13241.743589,18293.513050,0.000000,202.300588,24251.948919,35015.173905,20443.421948,0.000000,0.000000,832.963450,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_033_Vglut1,1964.924881,9988.940591,989.631869,305.247710,0.000000,9766.612592,9984.737784,0.000000,0.000000,5772.010072,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_021_Crh,0.000000,3097.680155,0.000000,2402.307909,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_088_Sst,0.000000,3382.488350,0.000000,459.928514,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_031_Vglut1,45732.837545,1312.766809,0.000000,0.000000,2729.331923,0.000000,0.000000,44563.517432,0.000000,8366.640757,...,1092.286950,1621.209588,355.115670,3065.887096,487.144274,0.000000,8616.857046,2795.464027,2559.91932,0.000000
221058_113_Sst,0.000000,20750.510421,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,164.086505,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251034_003_Vglut1,6368.725433,6740.504038,43749.397999,629.587737,17372.033400,8909.356375,9835.244075,18338.850338,0.000000,6274.965722,...,5038.139710,824.234013,5563.895841,2346.218196,1179.352044,2438.062616,0.000000,235.324882,0.00000,4407.917560
251034_004_Vglut1,70356.336579,3883.819883,22482.225571,1034.084054,147.075428,0.000000,799.162656,0.000000,0.000000,2505.711749,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
234172_034_Crh,0.000000,5973.432603,0.000000,3318.236579,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
251039_022_Vglut1,1099.173629,6698.274418,16319.485966,8314.918935,23742.288239,0.000000,0.000000,0.000000,0.000000,2169.777685,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
221058_042_Sst,0.000000,1.241491,0.000000,1899.077710,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
sum,518429.825622,411012.867998,270130.735692,241813.753491,227394.058864,207399.907656,184750.218711,125804.735540,119627.722412,116021.938105,...,12260.853319,4890.887202,11838.023022,10824.210585,3332.992637,4876.125232,17233.714091,6061.577817,5119.83864,8815.835119

In [61]:
# contra_ipsi
df.loc["group1",:] = "" 
def get_the_group(x):
    side = x.name.split("_")[1]
    if side == "contra":
        return "90_contra"
    else:
        dftmp = pd.read_csv("df_tmp.csv",index_col=0)
        area = dfregion.loc[dfregion["region"] == x.name.split("_")[0]].group.tolist()[0]
        return dftmp.loc[side+"_"+area,:].values[0]
    # side+"_"+area
    # return area
df.loc["group1",:] = df.apply(get_the_group, axis=0)

C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""
C:\Users\zljia\AppData\Local\Temp\ipykernel_16084\2710797454.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc["group1",:] = ""

In [27]:
dftmp = pd.read_csv("df_tmp.csv",index_col=0)

In [31]:
dftmp.loc["ipsi_STR",:].values[0]

'2_ipsi_STR'

In [ ]:

df.loc["group1",:] = "" 
def get_the_group(x):
    # print(x.name)
    return dfregion.loc[dfregion["region"] == x.name].group.tolist()[0]
df.loc["group1",:] = df.apply(get_the_group, axis=0)

In [63]:
df.loc["group1",:]

CP_ipsi         2_ipsi_STR
BLA_ipsi      1_ipsi_CTXsp
OT_ipsi         2_ipsi_STR
CEA_ipsi        2_ipsi_STR
ACB_ipsi        2_ipsi_STR
                  ...
PIR_contra       90_contra
SSp_contra       90_contra
SSs_contra       90_contra
MOp_contra       90_contra
ENT_contra       90_contra
Name: group1, Length: 65, dtype: object

In [50]:
df50.index.tolist()[0:-1]

['251034_010_Vglut1',
 '234172_015_Crh',
 '221058_038_Sst',
 '221058_107_Sst',
 '221297_038_Sst',
 '234172_031_Crh',
 '252460_132_Sst',
 '221058_040_Sst',
 '234172_016_Crh',
 '242655_057_Sst',
 '234172_017_Crh',
 '251039_029_Vglut1',
 '230058_076_Sst',
 '230058_078_Sst',
 '252459_079_Sst',
 '230058_074_Sst',
 '251039_021_Vglut1',
 '251034_001_Vglut1',
 '234172_020_Crh',
 '221058_071_Sst',
 '221297_036_Sst',
 '221058_104_Sst',
 '252459_074_Sst',
 '234172_019_Crh',
 '221297_037_Sst',
 '230058_073_Sst',
 '234172_122_Crh',
 '234172_086_Crh',
 '251039_020_Vglut1',
 '251039_033_Vglut1',
 '234172_021_Crh',
 '221058_088_Sst',
 '251039_031_Vglut1',
 '221058_113_Sst',
 '251034_003_Vglut1',
 '251034_004_Vglut1',
 '234172_034_Crh',
 '251039_022_Vglut1',
 '221058_042_Sst']

In [64]:
df.iloc[-1:,:].to_csv("BLA_3_plot_65.csv")

In [42]:
dfinfor = pd.read_csv(r"J:\BLA_four_types\bilateral\BLA_geno_location2.csv",index_col=0)

In [51]:
dfinfor = dfinfor.loc[df50.index.tolist()[0:-1]]

In [52]:
dfinfor.to_csv("BLA_geno_location2.csv")

In [ ]:
dfinfor = pd.read_excel(r"BLA_CCK_all_infor_type_new.xlsx",index_col=0)

In [ ]:
dfinfor[["cluster"]].to_csv("top60_cluster.csv")

In [ ]:
dfinfor[['neuron', 'location', 'type']].to_csv("BLA_cck_geno_label.csv")

In [ ]:
newlist = df.index.tolist()[0:-1]

In [ ]:
dfi = pd.DataFrame(index=newlist)

In [ ]:
dfi["geno"] = "Sst"

In [ ]:
dfi["location"] = ["TU" if item.split("_")[-1] == "TU" else "Others" for item in dfi.index.tolist()]

In [ ]:
dfi.to_csv("Tu_Sst_infor.csv")

In [ ]:
df["geno"]= [item.split("_")[2] for item in df.index.tolist()]

In [ ]:
df[["geno"]].to_csv("labels_MPOA.csv")

In [ ]:
df["geno"].value_counts()

In [ ]:
dfHY = df.loc[:,df.loc["group1",:]=="HY"]

In [ ]:
dfHY = dfHY.drop("group1",axis=0)

In [ ]:
dfHY = dfHY.drop("HY",axis=1)

In [ ]:
dfHY.to_excel("MO_all_0110_HY.xlsx")

In [ ]:
df.to_csv("_plots.csv")

In [ ]:
df = pd.read_excel(os.path.join(Datapath,"PAG_subregion_double_side_cluster.xlsx"),index_col=0)
# dfcluster = pd.read_excel(os.path.join(Datapath,"cluster_all_30_new.xlsx"),index_col=0)
# dfregion = pd.read_excel(os.path.join(Datapath,"brain_areas.xlsx"),index_col=0)
# df = pd.read_csv(os.path.join(Datapath,"HY_neurons.csv"),index_col=0)

In [ ]:
dfnew= df.loc[df.cluster>15]

In [ ]:
dfnew["neuron"] = dfnew.index.str[0:10]

In [ ]:
dfPAG  =dfnew.set_index("neuron").drop("cluster",axis=1)

In [ ]:
df.iloc[-1:,:].to_csv("MO_HY_plots.csv")

In [ ]:
df.to_csv("LCB_top50.csv")

In [ ]:
# add pickcle list
import pickle
with open("area_list.pkl","rb") as f:
    arealist = pickle.load(f)

In [ ]:
df = df[arealist]

In [ ]:
df

In [ ]:
os.chdir(r"E:\20221011_figs\20221031 POA")

In [ ]:
df = pd.read_csv(".\\Tac2\\Tac2_neurons_top50.csv",index_col=0,sep=",")
df.loc["group1",:] = "" 
def get_the_group(x):
    # print(x.name)
    return dfregion.loc[dfregion["region"] == x.name].group.tolist()[0]
df.loc["group1",:] = df.apply(get_the_group, axis=0)
df.iloc[-1:,:].to_csv(".\\Tac2\\Tac2_neurons_label.csv")

In [ ]:
df = df.drop("CTXsp",axis =1)

In [ ]:
df

In [ ]:
df.to_csv(os.path.join(Datapath,"all_neuron_1013_data.csv"))

In [ ]:
df.to_excel(os.path.join(Datapath,"all_neuron_1013_label.xlsx"))

In [ ]:
df.loc["group1",:] = "" 
def get_the_group(x):
    # print(x.name)
    return dfregion.loc[dfregion["region"] == x.name].group.tolist()[0]
df.loc["group1",:] = df.apply(get_the_group, axis=0)

In [ ]:
df.loc["group2",:] = "" 
def get_the_group2(x):
    return dfregion.loc[dfregion["region"] == x.name].hypothalamus.tolist()[0]
df.loc["group2",:] = df.apply(get_the_group2, axis=0)

In [ ]:
df

In [ ]:
df.iloc[-1:,:].to_csv(os.path.join(Datapath,"MBO_label_1110.csv"))

In [ ]:
df.to_csv(os.path.join(Datapath,"Esr1_data_1106_51.csv"))

In [ ]:
df.loc[:,df.loc["group1",:]=="HY"].iloc[0:-1,:]

In [ ]:
df.loc[:,df.loc["group1",:]=="TH"].iloc[0:-1,:].to_csv("orexin_neurons_0926_TH.csv")

In [ ]:
df

In [ ]:

dfnew = pd.concat([df,dfcluster],axis=1)

In [ ]:
df.to_csv(os.path.join(Datapath,"0712_neurons_for_cluster.csv"))

In [ ]:
# add module change the order as the score matrix
dfneuron = pd.read_excel("all_neurons_0714_level8_top50.xlsx",index_col=0)
dfscore = pd.read_csv("morpho_score_220628.csv",sep = ",",index_col=0)

In [ ]:
def get_wendu_type(x):
    return x.name[0:10]
dfneuron.loc[:, "neuron"] = dfneuron.apply(get_wendu_type, axis=1)
dfnew = dfneuron.set_index("neuron")

In [ ]:
dforder = dfscore.iloc[:,1:3]
dforder.columns =["aa","bb"]
dfdata = pd.concat([dforder,dfnew],axis =1)
dfnow = dfdata.drop(["aa","bb"],axis = 1)
dfnow.to_excel("0712_all_projection_for_matrix.xlsx")
dfnow.to_csv("0712_all_projection_for_matrix.csv")

In [ ]:
df = dfnow
df.loc["group1",:] = "" 
def get_the_group(x):
    # print(x.name)
    return dfregion.loc[dfregion["region"] == x.name].group.tolist()[0]
df.loc["group1",:] = df.apply(get_the_group, axis=0)

In [ ]:
df.iloc[-11:,:].to_csv("0807_neurons_for_group.csv")

In [ ]:
dfnow.to_csv("0712_neurons_all.csv")

In [ ]:
df.iloc[-1:,:]

In [ ]:
import pickle,os
DataPath = r"E:\20220210_for_figs\0616 cluster\nbl_2_5"
PklPath = os.path.join(DataPath,"aba_dist_HY_nblast_2_5.pkl")
neuronsPath = os.path.join(DataPath,"neuron_list_HY_non_nor.pkl")
with open(PklPath,"rb") as f:
    aba_dist = pickle.load(f)
with open(neuronsPath,"rb") as f:
    n = pickle.load(f)

In [ ]:
index_name = []
for neuron in n:
    index_name.append(neuron.name[0:10])
aba_dist.columns = index_name
aba_dist.index = index_name
aba_dist.to_csv(os.path.join(DataPath,"HY_dist.csv"))

In [ ]:
dfdata = pd.read_excel("PAG_Subarea_projection_length_data.xlsx",index_col=0)

In [ ]:
dfdata.set_index("neuron").to_csv("PAG_Subarea_projection_length_data.csv")

In [ ]:
dfplot = pd.read_excel("PAG_Subarea_projection_length_plot.xlsx",index_col=0)
dfplot.set_index("neuron").to_csv("PAG_Subarea_projection_length_plot.csv")

In [ ]:
dftac1 = df.loc[df.index.str.contains("Tac1")]

In [ ]:
dftac1_p = dftac1[["PAG","VTA"]]

In [ ]:
VPlist = []
for geno in df.geno.value_counts().index.tolist():
    dftmp = df.loc[df.index.str.contains(geno)]
    dftmp_p = dftmp[["PAG","VTA"]]
    dftmp_p.loc[(dftmp_p.VTA>0)|(dftmp_p.PAG>0)]
    geno_dic = {}
    geno_dic["geno"] = geno
    geno_dic["VTA&PAG"] = len(dftmp_p.loc[(dftmp_p.VTA>0)&(dftmp_p.PAG>0)])
    geno_dic["only_PAG"] = len(dftmp_p.loc[(dftmp_p.VTA==0)&(dftmp_p.PAG>0)])
    VPlist.append(geno_dic)

In [ ]:
dfVP = pd.DataFrame(VPlist)

In [ ]:
dfVP.to_excel("VTA&PAG.xlsx")

In [ ]:
dfall = pd.read_excel("mPOA_neurons_0418_chose_small.xlsx",index_col =0)

In [ ]:
dfcluster = pd.read_excel("MPO_cluster_9.xlsx",index_col=0)

In [ ]:
df2 = pd.concat([dfcluster.cluster,dfall],axis=1)

In [ ]:
df2.to_excel("mPOA_neurons_0418_chose_cluster.xlsx")

In [68]:
dftmp = pd.DataFrame(os.listdir(r"J:\BLA_four_types\soma"))

In [76]:
dftmp.colums = ["file"]

In [85]:
dftmp["neuron"] = [item[0:10] for item in  dftmp[0].tolist()]
dftmp["location"] = [item.split("_")[3] for item in  dftmp[0].tolist()]
dftmp["geno"] = [item.split("_")[2] for item in  dftmp[0].tolist()]
dftmp["file"] = dftmp["neuron"]+"_"+dftmp["geno"]

In [ ]:
dfdata.loc[dfmatrix.index.tolist()].to_csv(r"BLA_neurons_0819_top72.csv")

In [91]:
dftmp2 = dftmp[["file","geno","location"]].set_index("file").loc[dfmatrix.index.tolist()]

In [92]:
dftmp2.to_csv("BLA_geno_location2.csv")

In [93]:
dftmp2.location.unique()

array(['BLAa', 'ec', 'CEAc', 'STR', 'BLAp', 'BLAv'], dtype=object)