In [2]:
import os,sys
import pandas as pd
from change_level import brain_level
# os.chdir(r"H:\20240822_figs\20240903_XSJ_lab_hypothalamus")
# os.chdir(r"H:\20240822_figs\20240928_XSJ_lab")
# os.chdir(r"H:\20240822_figs\20241001_Tu_Sst")
os.chdir(r"J:\BLA_three_types\bilateral")

In [2]:
dfdata = pd.read_csv("allen_volume.csv",sep = ",",index_col=0)

In [7]:
dfdata = pd.read_excel("all_neurons_1123_ispi_bottom.xlsx",index_col=0)

In [4]:
dfdata = dfdata.T

In [9]:
dfn = dfdata.loc[:,dfdata.loc["voxel",:]!=0]

In [5]:
dfdata

,TMv,SCig,IPN,eps,eps,PMv,AUDp6b,SSp-tr1,SIM,GENd,...,ccs,P-mot,ECT5,FN,AUDv4,mfbs,MOs,AId1,root,FS
voxel,107802,2037504,11050,0,0,195022,55246,205640,5696048,0,...,744958,0,529802,502036,213616,0,0,459546,3557422,428468

In [17]:
aa = dfn.columns.to_list()

In [20]:
dfdata = dfdata.drop(aa,axis=1)

In [3]:
dfdata = pd.read_excel("All_neurons_1116_bottom.xlsx",index_col=0)

In [11]:
df = pd.read_csv("projection_length_contra.csv",index_col =0)

In [3]:
dfdata = pd.read_csv("projection_length_contra.csv",index_col =0)
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="level_8_map_cortex friendly_change_swc_BLA.xlsx")
dfnew = bl.up_projection2level_exist(morelist= back)
dfnew.to_excel("projection_length_contra_combine.xlsx")

high level areas exist, run up_projection2level_exist

In [4]:
dfdata = pd.read_csv("projection_length_ipsi.csv",index_col =0)
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="level_8_map_cortex friendly_change_swc_BLA.xlsx")
dfnew = bl.up_projection2level_exist(morelist= back)
dfnew.to_excel("projection_length_ipsi_combine.xlsx")

high level areas exist, run up_projection2level_exist

In [20]:
dfdata = pd.read_csv("projection_length_ipsi.csv",index_col =0)
df_cleaned = dfdata.loc[~(dfdata == 0).all(axis=1)]

In [23]:
df_cleaned = dfdata.loc[~(dfdata == 0).all(axis=1)]

In [ ]:
# 保留至少有一个值不是0的列
df_cleaned = df.loc[:, (df != 0).any(axis=0)]

In [25]:
df_cleaned = dfdata.loc[:, ~(dfdata == 0).all(axis=0)]

In [37]:
aa = set(df_cleaned.columns.tolist()) &set(map_dic["MY"])

In [40]:
list(aa)

['SPVC',
 'LIN',
 'AMBv',
 'DMX',
 'PGRNl',
 'IRN',
 'NTS',
 'MDRNd',
 'AMBd',
 'VII',
 'PARN']

In [ ]:
df_cleaned[list(aa)+["MY"]].to_excel(r"J:\BLA_three_types\MY2.xlsx")

:

In [ ]:

set(map_dic["MY"])

['IO',
 'DCO',
 'VCO',
 'ISN',
 'IRN',
 'AMBv',
 'PRP',
 'NR',
 'MV',
 'LIN',
 'RM',
 'AP',
 'LAV',
 'SUV',
 'RO',
 'SPIV',
 'RPA',
 'MARN',
 'ICB',
 'SPVC',
 'SPVI',
 'SPVO',
 'ACVII',
 'NTB',
 'NTS',
 'VI',
 'VII',
 'CU',
 'x',
 'XII',
 'y',
 'DMX',
 'PARN',
 'PAS',
 'ECU',
 'AMBd',
 'LRNm',
 'LRNp',
 'PGRNd',
 'PGRNl',
 'GR',
 'GRN',
 'PPY',
 'MDRNd',
 'MDRNv',
 'Pa5']

In [32]:
list[set(df_cleaned.columns.tolist()) &set(map_dic["MY"])]

list[{'SPVC', 'LIN', 'AMBv', 'DMX', 'PGRNl', 'IRN', 'NTS', 'MDRNd', 'AMBd', 'VII', 'PARN'}]

In [4]:
dfnew["KF"]

KeyError: 'KF'

In [5]:
dfdata = pd.read_csv("terminal_count_ipsi.csv",index_col =0)
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="level_8_map_cortex friendly_change_swc.xlsx")
dfnew = bl.up_projection2level_exist(morelist= back)
dfnew.to_excel("terminal_count_ipsi_combine.xlsx")

high level areas exist, run up_projection2level_exist

In [6]:
dfdata = pd.read_csv("terminal_count_contra.csv",index_col =0)
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="level_8_map_cortex friendly_change_swc.xlsx")
dfnew = bl.up_projection2level_exist(morelist= back)
dfnew.to_excel("terminal_count_contra_combine.xlsx")

high level areas exist, run up_projection2level_exist

In [3]:
dfdata = pd.read_csv("projection_length_ipsi.csv",index_col =0)
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="level_8_map_cortex friendly_change_swc.xlsx")
dfnew = bl.up_projection2level_exist(morelist= back)
dfnew.to_excel("projection_length_ipsi_combine.xlsx")

high level areas exist, run up_projection2level_exist

In [ ]:
dfdata = dfdata.stack().unstack(0)

In [8]:
# dfmap = pd.read_excel("level_8_map.xlsx",index_col=0)
dfdata = pd.read_excel("Esr1_neurons_combine_0229_bottom.xlsx",index_col=0)
# areas = dfdata.columns.tolist()
# target = dfmap.child.tolist()

In [3]:
dfdata

,AAA,AHN,ARH,CEAc,CEAl,CEAm,FS,LHA,MPO,PSTN,...,AUDv6b,von,ORBm6b,c,vhc,SSp-un4,AId6b,SSp-tr4,VISrl4,LGd-ip
192710_002_Pomc_TU,4,12,2,18,15,145,10,5,1,1,...,0,0,0,0,0,0,0,0,0,0
192710_003_Pomc_TU,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192710_004_Pomc_TU,0,13,0,0,0,0,0,2,29,0,...,0,0,0,0,0,0,0,0,0,0
192710_005_Pomc_TU,0,10,1,0,0,0,0,5,30,0,...,0,0,0,0,0,0,0,0,0,0
192710_007_Pomc_PMv,0,0,0,0,0,0,0,20,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220102_131_Crh_VMH,0,3,0,0,0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
220102_139_Crh_DMH,0,0,0,0,0,20,0,17,0,9,...,0,0,0,0,0,0,0,0,0,0
220102_147_Crh_HY,0,0,0,0,0,0,0,6,0,0,...,0,0,0,0,0,0,0,0,0,0
220102_148_Crh_HY,2,0,0,0,0,0,0,50,0,0,...,0,0,0,0,0,0,0,0,0,0
220102_149_Crh_DMH,0,0,0,0,0,0,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
os.chdir(r"H:\all_neurons_1116")

In [2]:
dfdata = pd.read_excel("VTA_neurons_0401_bottom.xlsx",index_col=0)

In [ ]:
bl = brain_level()
bl.export_level_file(i=3)

In [ ]:
bl = brain_level()
contain,back = bl.check_high_level_area(dfdata=dfdata,level=7)

In [11]:
dfdata = dfn

In [8]:
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="level_for_Tu.xlsx")

high level areas exist, run up_projection2level_exist

In [9]:
map_dic

{'CEA': ['CEAc', 'CEAl', 'CEAm'],
 'TM': ['TMv', 'TMd'],
 'MG': ['MGm', 'MGv', 'MGd'],
 'SPF': ['SPFp', 'SPFm'],
 'LS': ['LSv', 'LSr', 'LSc'],
 'IPN': ['IPA', 'IPC', 'IPDM', 'IPR', 'IPL', 'IPRL', 'IPDL', 'IPI'],
 'BMA': ['BMAa', 'BMAp'],
 'SCm': ['SCdg', 'SCdw', 'SCig', 'SCiw'],
 'IC': ['ICe', 'ICd', 'ICc'],
 'AM': ['AMd', 'AMv'],
 'ILA': ['ILA1', 'ILA2/3', 'ILA5', 'ILA6a', 'ILA6b'],
 'MM': ['MMd', 'MMl', 'MMm', 'MMme', 'MMp'],
 'NLOT': ['NLOT3', 'NLOT2', 'NLOT1'],
 'ORBm': ['ORBm5', 'ORBm6a', 'ORBm1', 'ORBm2/3', 'ORBm6b'],
 'LRN': ['LRNm', 'LRNp'],
 'PGRN': ['PGRNl', 'PGRNd'],
 'SOC': ['SOCl', 'POR', 'SOCm'],
 'MDRN': ['MDRNd', 'MDRNv'],
 'COAp': ['COApl', 'COApm'],
 'LGd': ['LGd-co', 'LGd-ip', 'LGd-sh'],
 'BLA': ['BLAa', 'BLAp', 'BLAv'],
 'AId': ['AId5', 'AId6a', 'AId6b', 'AId2/3', 'AId1'],
 'AIp': ['AIp6a', 'AIp1', 'AIp2/3', 'AIp5', 'AIp6b'],
 'AIv': ['AIv5', 'AIv6a', 'AIv1', 'AIv2/3', 'AIv6b'],
 'ECT': ['ECT6a', 'ECT6b', 'ECT1', 'ECT2/3', 'ECT5'],
 'ENTl': ['ENTl3', 'ENTl5', 'ENTl6a', 'ENTl2', 'ENTl1'],
 'ORBl': ['ORBl5', 'ORBl6a', 'ORBl6b', 'ORBl2/3', 'ORBl1'],
 'PERI': ['PERI6a', 'PERI6b', 'PERI1', 'PERI2/3', 'PERI5'],
 'AMB': ['AMBd', 'AMBv'],
 'DG': ['DG-mo', 'DG-po', 'DG-sg'],
 'ACAd': ['ACAd1', 'ACAd5', 'ACAd6a', 'ACAd6b', 'ACAd2/3'],
 'ACAv': ['ACAv1', 'ACAv2/3', 'ACAv5', 'ACAv6a', 'ACAv6b'],
 'PL': ['PL1', 'PL2/3', 'PL5', 'PL6a', 'PL6b'],
 'ENTm': ['ENTm5', 'ENTm6', 'ENTm2', 'ENTm1', 'ENTm3'],
 'GU': ['GU5', 'GU6a', 'GU1', 'GU2/3', 'GU4', 'GU6b'],
 'MOp': ['MOp6a', 'MOp2/3', 'MOp5', 'MOp1', 'MOp6b'],
 'ORBvl': ['ORBvl6a', 'ORBvl5', 'ORBvl1', 'ORBvl2/3', 'ORBvl6b'],
 'RSPv': ['RSPv6a', 'RSPv6b', 'RSPv1', 'RSPv2/3', 'RSPv5'],
 'SSs': ['SSs6a', 'SSs1', 'SSs2/3', 'SSs4', 'SSs5', 'SSs6b'],
 'VISC': ['VISC1', 'VISC2/3', 'VISC4', 'VISC5', 'VISC6a', 'VISC6b'],
 'FRP': ['FRP6a', 'FRP5', 'FRP1', 'FRP2/3', 'FRP6b'],
 'MOs': ['MOs6a', 'MOs5', 'MOs2/3', 'MOs6b', 'MOs1'],
 'RSPagl': ['RSPagl6a', 'RSPagl1', 'RSPagl6b', 'RSPagl2/3', 'RSPagl5'],
 'SSp-tr': ['SSp-tr6a',
  'SSp-tr5',
  'SSp-tr6b',
  'SSp-tr1',
  'SSp-tr2/3',
  'SSp-tr4'],
 'VISa': ['VISa6a', 'VISa1', 'VISa6b', 'VISa2/3', 'VISa4', 'VISa5'],
 'AUDv': ['AUDv1', 'AUDv2/3', 'AUDv5', 'AUDv6a', 'AUDv6b', 'AUDv4'],
 'TEa': ['TEa1', 'TEa6a', 'TEa6b', 'TEa5', 'TEa2/3', 'TEa4'],
 'VISpor': ['VISpor6a',
  'VISpor6b',
  'VISpor1',
  'VISpor2/3',
  'VISpor4',
  'VISpor5'],
 'AUDd': ['AUDd1', 'AUDd2/3', 'AUDd4', 'AUDd5', 'AUDd6a', 'AUDd6b'],
 'AUDp': ['AUDp1', 'AUDp2/3', 'AUDp6a', 'AUDp4', 'AUDp5', 'AUDp6b'],
 'RSPd': ['RSPd1', 'RSPd2/3', 'RSPd6a', 'RSPd6b', 'RSPd5'],
 'SSp-bfd': ['SSp-bfd1',
  'SSp-bfd2/3',
  'SSp-bfd4',
  'SSp-bfd5',
  'SSp-bfd6a',
  'SSp-bfd6b'],
 'SSp-ll': ['SSp-ll5',
  'SSp-ll1',
  'SSp-ll2/3',
  'SSp-ll6a',
  'SSp-ll6b',
  'SSp-ll4'],
 'SSp-m': ['SSp-m6a', 'SSp-m6b', 'SSp-m1', 'SSp-m2/3', 'SSp-m4', 'SSp-m5'],
 'SSp-ul': ['SSp-ul5',
  'SSp-ul6a',
  'SSp-ul6b',
  'SSp-ul1',
  'SSp-ul2/3',
  'SSp-ul4'],
 'SSp-un': ['SSp-un5',
  'SSp-un6a',
  'SSp-un1',
  'SSp-un4',
  'SSp-un2/3',
  'SSp-un6b'],
 'VISam': ['VISam1', 'VISam5', 'VISam6a', 'VISam4', 'VISam2/3', 'VISam6b'],
 'VISp': ['VISp5', 'VISp6a', 'VISp6b', 'VISp1', 'VISp2/3', 'VISp4'],
 'VISpm': ['VISpm1', 'VISpm2/3', 'VISpm4', 'VISpm5', 'VISpm6b', 'VISpm6a'],
 'VISrl': ['VISrl1', 'VISrl4', 'VISrl5', 'VISrl6a', 'VISrl6b', 'VISrl2/3'],
 'AOB': ['AOBgl', 'AOBmi', 'AOBgr'],
 'SSp-n': ['SSp-n5', 'SSp-n6a', 'SSp-n1', 'SSp-n2/3', 'SSp-n4', 'SSp-n6b'],
 'VISal': ['VISal1', 'VISal2/3', 'VISal4', 'VISal5', 'VISal6a', 'VISal6b'],
 'VISl': ['VISl2/3', 'VISl4', 'VISl6b', 'VISl6a', 'VISl1', 'VISl5'],
 'VISli': ['VISli1', 'VISli2/3', 'VISli4', 'VISli6a', 'VISli6b', 'VISli5'],
 'VISpl': ['VISpl4', 'VISpl5', 'VISpl6a', 'VISpl1', 'VISpl2/3', 'VISpl6b'],
 'AUDpo': ['AUDpo6a', 'AUDpo6b', 'AUDpo1', 'AUDpo2/3', 'AUDpo4', 'AUDpo5']}

In [6]:
dfdata = df

In [11]:
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="level_8_map_cortex friendly for vol.xlsx")

high level areas exist, run up_projection2level_exist

In [ ]:
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="level_8_map_cortex friendly_change_swc.xlsx")
dfnew = bl.up_projection2level_exist(morelist= back)
dfnew.to_excel("all_neurons_BLA_0818.xlsx")

high level areas exist, run up_projection2level_exist

In [7]:
dfnew = bl.up_projection2level()
dfnew.to_excel("allen_volume_level_8_map_cortex friendly_change_swc.xlsx")

In [ ]:
dfnew.stack().unstack(0).to_excel("soma_level7.xlsx")

In [ ]:
dfnew.to_csv("all_neurons_0916_HY_MY_level8.csv")

In [10]:
back

['MY', 'PB', 'IPN']

In [24]:
dfnew = bl.up_projection2level_exist(morelist= back)
dfnew.to_excel("all_neurons_BLA_0818.xlsx")

In [13]:
df_cleaned = dfnew.loc[:, (dfnew != 0).any(axis=0)]

In [16]:
df_cleaned.to_excel("all_neurons_BLA_0818_clean.xlsx")

In [17]:
# top50 areas
dfnew.loc["sum"] =dfnew.apply(lambda x:x.sum(),axis =0)
dfnew = dfnew.sort_values(by = "sum",axis=1,ascending=False)
dfnew2 = dfnew.iloc[:,0:60]
df50  =dfnew2.drop(labels='sum',axis=0) 
df50.to_excel(os.path.join("BLA_neurons_0304_top60.xlsx"))

In [18]:
df50

,CEA,BLA,CP,OT,SI,ACB,STR,PL,BMA,ORB,...,aco,NTS,ECT,st,PA,CENT2,LPO,MA,PAA,P
251034_010_Vglut1,182.021610,2288.150423,18477.969476,31361.328165,4183.218033,12177.902425,988.185615,11843.636658,0.000000,16751.79463,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,14.418769,0.0,0.000000
234172_015_Crh,134.399439,2970.330035,0.000000,0.000000,0.000000,0.000000,314.840716,0.000000,0.000000,0.00000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000
234065_020_Pkc,1845.727861,2217.443320,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000
221058_038_Sst,5631.989116,8255.673888,1156.533573,0.000000,3576.375407,75.257641,2392.741058,0.000000,111.493625,0.00000,...,111.175397,0.0,0.0,538.003731,0.0,535.871089,0.0,0.000000,0.0,67.438845
234065_009_Pkc,4193.575312,2924.121064,0.000000,0.000000,4609.224952,269.019952,1112.492179,0.000000,692.110508,0.00000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234065_015_Pkc,4688.749945,3346.643616,0.000000,0.000000,892.944507,0.000000,248.231979,0.000000,7.843124,0.00000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000
242657_002_Pkc,15535.340937,3575.094118,0.000000,0.000000,7282.834435,902.733458,932.615846,0.000000,585.099589,0.00000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000
242658_044_Pkc,1247.448310,4322.818749,0.000000,0.000000,0.000000,0.000000,714.852657,0.000000,253.414019,0.00000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000
234065_016_Pkc,10456.780353,7294.394644,0.000000,0.000000,329.831975,0.000000,1317.854124,0.000000,1472.941999,0.00000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000
242657_038_Pkc,5595.878310,2064.018961,0.000000,0.000000,1595.109521,0.000000,1902.366372,0.000000,220.863619,0.00000,...,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.000000

In [20]:
dfHY_Volume = dfnew[arealist].T

In [21]:
dfHY_Volume.to_csv("HY_area_volume.csv")

In [21]:
dfnew["PVp"]

192710_002_Pomc_TU     0
192710_003_Pomc_TU     0
192710_004_Pomc_TU     0
192710_005_Pomc_TU     0
192710_007_Pomc_PMv    0
                      ..
220102_131_Crh_VMH     0
220102_139_Crh_DMH     0
220102_147_Crh_HY      0
220102_148_Crh_HY      0
220102_149_Crh_DMH     0
Name: PVp, Length: 7180, dtype: int64

In [15]:
dfindex = pd.read_excel("SpeciesBrainRegion-XSJ_index.xlsx",index_col=0)

In [16]:
arealist = dfindex.Assign_Simple.unique().tolist()

In [17]:
arealist

['PVH',
 'ARH',
 'SHy',
 'POA',
 'AVPe',
 'DMH',
 'MnPO',
 'OV',
 'StHy',
 'PS',
 'PVp',
 'AMPO',
 'SBPV',
 'SCH',
 'SFO',
 'VLPO',
 'AHN',
 'MBO',
 'PM',
 'VMH',
 'PH',
 'LHA',
 'LPO',
 'pZI',
 'PeF',
 'RCH',
 'TU',
 'ZI',
 'SO']

In [25]:
arealist.remove("SFO")

In [27]:
arealist

['PVH',
 'ARH',
 'SHy',
 'POA',
 'AVPe',
 'DMH',
 'MnPO',
 'OV',
 'StHy',
 'PS',
 'PVp',
 'AMPO',
 'SBPV',
 'SCH',
 'VLPO',
 'AHN',
 'MBO',
 'PM',
 'VMH',
 'PH',
 'LHA',
 'LPO',
 'pZI',
 'PeF',
 'RCH',
 'TU',
 'ZI',
 'SO']

In [26]:
dfnew[arealist].to_excel("HY_neurons_terminals_0903_HY.xlsx")

In [6]:
dflabel = pd.read_csv("all_neurons_plots_new.csv",index_col=0,sep=",")

In [4]:
bl = brain_level()
contain,back,map_dic = bl.check_self_define_level(dfdata=dfdata,file="combine_MPOA_pathways_in_HY.xlsx")

high level areas exist, run up_projection2level_exist

In [5]:
dfnew = bl.up_projection2level_exist(morelist= back)
dfnew.to_excel("To_ZI_neurons_chose_0304.xlsx")

In [5]:
dfnew

,MPO,BST,MPN,AHN,RCH,VMH,AVPV,PS,PeF,ADP,...,PMv+,Dorsal hypothalamus,ACB-LS,PB+,Paraventricular,VTA+,Dorsal thalamus,PCG+,Amygdala,MS-NDB-CA1
180712_001_Esr1_MPN,3286.412109,344.095154,655.472900,3683.525391,0.000000,27.911901,252.484650,1012.389648,303.736389,684.345520,...,3673.222656,7442.124023,3738.346314,1347.834732,2128.121399,0.000000,202.336151,0.000000,0.000000,3267.302857
180712_002_Esr1_MPN,532.509827,0.000000,2294.634521,4103.925781,191.849289,148.924866,593.506592,0.000000,533.284912,0.000000,...,4294.544815,4416.210357,146.901627,0.000000,203.225235,0.000000,0.000000,0.000000,0.000000,0.000000
180712_004_Esr1_MPN,938.441895,1108.049561,519.646423,4155.762207,839.635193,289.743958,0.000000,1093.648071,0.000000,0.000000,...,5744.854981,5110.624599,0.000000,12036.046677,0.000000,2220.013428,0.000000,0.000000,867.226929,325.020081
180712_005_Esr1_MPN,1511.008545,1847.482422,131.324539,0.000000,1316.721680,1036.184326,1547.397095,41.849136,0.000000,297.519897,...,13834.059723,3037.547851,1220.202393,5699.442627,8730.541717,2966.242522,0.000000,0.000000,0.000000,0.000000
180712_006_Esr1_VMPO,1705.437134,977.864075,521.481689,1623.054077,128.244751,1005.521912,769.602051,269.856415,216.769501,0.000000,...,10163.770385,7258.805908,620.221619,760.097832,7030.426087,1589.998382,698.855164,5456.612793,0.000000,2297.394043
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212202_037_Trh_MPN,3071.869385,3881.594971,4205.163086,240.785126,0.000000,0.000000,1126.397339,61.408066,534.612976,779.274719,...,2941.624878,3399.110473,939.111633,0.000000,10727.178222,0.000000,0.000000,0.000000,0.000000,149.830566
212202_044_Trh_MPN,0.000000,0.000000,397.364746,859.363586,469.871002,0.000000,0.000000,0.000000,0.000000,0.000000,...,888.101624,0.000000,0.000000,0.000000,1663.911438,0.000000,0.000000,0.000000,0.000000,0.000000
212202_051_Trh_LPO,204.596909,0.000000,0.000000,490.446442,0.000000,0.000000,0.000000,0.000000,106.906448,0.000000,...,876.489791,1781.716785,3296.969666,0.000000,0.000000,0.000000,0.000000,276.061218,0.000000,0.000000
212202_060_Trh_HY,796.176636,3196.668945,5603.453125,1355.962524,771.991394,0.000000,0.000000,0.000000,0.000000,812.372131,...,9318.386230,1162.066111,5443.873413,0.000000,1837.466676,0.000000,0.000000,0.000000,5130.398306,0.000000
212202_061_Trh_HY,193.510086,3336.179932,0.000000,0.000000,0.000000,0.000000,0.000000,66.822380,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [8]:
dfnew[dflabel.columns.to_list()].to_csv("all_neurons_terminal_0901_chose_Fig1_plot.csv")

In [7]:
# top50 areas
dfnew.loc["sum"] =dfnew.apply(lambda x:x.sum(),axis =0)
dfnew = dfnew.sort_values(by = "sum",axis=1,ascending=False)
dfnew2 = dfnew.iloc[:,0:110]
df50  =dfnew2.drop(labels='sum',axis=0) 
df50.to_excel(os.path.join("To_ZI_neurons_0304_top100.xlsx"))

In [11]:
df50.to_csv(os.path.join("mPOA_neurons_0418_top50.csv"))

In [7]:
df50.to_csv(os.path.join("VTA_neurons_0401_top50.csv"))

In [ ]:
dfnew = pd.read_excel("mouse_neurons_1115_chose.xlsx",index_col=0)

In [ ]:
dflist = pd.read_csv(".\\heatmap\\all_neuron_data_1013.csv",index_col=0,sep=",")

In [ ]:
columnslist = dflist.columns.tolist()

In [ ]:
columnslist.remove('ME')
'

In [ ]:
columnslist.remove('PL')

In [ ]:
dfnew[columnslist]

In [ ]:
dfnew[columnslist].to_csv("mouse_neurons_1115_data.csv")

In [ ]:
dfnew.to_csv("Esr1_POA_neurons_1105_chose.csv")

In [ ]:
dfcluster = pd.read_excel("mean_cluster_31_noswc.xlsx",index_col=0)

In [ ]:
dfnew

In [ ]:
dfcom = pd.concat([dfcluster.cluster,dfnew],axis=1)

In [ ]:
dfcom.to_excel("All_neurons_1028_chose_cluster.xlsx")

In [ ]:
dfcortex = pd.read_excel(r"D:\python\pre-cube length\cortex areas.xlsx")

In [ ]:
listarea =  dfcortex.area.tolist()

In [ ]:
listarea

In [ ]:
dfnew[listarea].to_csv("CA1_neurons_1008_hip_Area.csv")

In [ ]:
dfnew.stack().unstack(0).to_excel("volumes_0929_level8_cortex.xlsx")

In [ ]:
dfnew[listarea]

In [ ]:
dfnew.loc[:,dfnew.iloc[0,:]==0].columns.tolist()

In [ ]:
dfnew.loc[:,dfnew.iloc[0,:]==0]

In [ ]:
dfHIP = dfnew.loc[dfnew.HIP >0]

In [ ]:
dfnew[back]

In [ ]:
dfnew.loc[dfnew.VS>0].to_excel("vs_debug.xlsx")

In [ ]:
dfHIP.to_excel("HIP_neurons_0921_level7.xlsx")

In [ ]:
# combine ispi and contra
dfispi = pd.read_excel("all_neurons_0923_ispi_level6.xlsx",index_col=0)
dfcontra = pd.read_excel("all_neurons_0923_contra_level6.xlsx",index_col=0)

In [ ]:
uselist = ['P-mot',
 'P-sat',
 'P-sen',
 'MY-mot',
 'MY-sat',
 'MY-sen']

In [ ]:
dfPM_ispi = dfispi[uselist]
dfPM_contra = dfcontra[uselist]

In [ ]:
new_col = []
for area in dfPM_contra.columns.tolist():
    new_col.append(area+"_contra")
dfPM_contra.columns = new_col

In [ ]:
new_col = []
for area in dfPM_ispi.columns.tolist():
    new_col.append(area+"_ispi")
dfPM_ispi.columns = new_col

In [ ]:
dfPM = pd.concat([dfPM_ispi,dfPM_contra],axis =1)

In [ ]:
dfPM.to_excel("all_neurons_0923_Pon_and_medulla.xlsx")

In [ ]:
dfcluster = pd.read_excel("mean_cluster_31_noswc.xlsx",index_col=0)

In [ ]:
dfnew_cluster = pd.concat([dfcluster.cluster,dfnew],axis =1)

In [ ]:
dfnew_cluster.to_excel("all_neurons_cluster_level8.xlsx")

In [ ]:
dfnew_cluster

In [ ]:
dfPM_MY = dfnew_cluster.loc[(dfnew_cluster.cluster>15)&(dfnew_cluster.cluster<22)]

In [ ]:
dfPM_MY.to_excel("MY_neurons_0923_cluster.xlsx")

In [ ]:
uselist.append("cluster")

In [ ]:
dfPM_MY[uselist].to_excel("MY_neurons_0923_cluster_only_areas.xlsx")

In [ ]:
dfHY = dfnew.loc[(dfnew.HY>0)|(dfnew.MY>0)]

In [ ]:
import shutil

In [ ]:
infile = r"E:\PFC\ORB\swc_raw"
outfile = r"E:\PFC\ORB\swc_HY"

In [ ]:
for file in dfHY.index.tolist():
    inname = os.path.join(infile,file+".swc")
    outname = os.path.join(outfile,file+".swc")
    shutil.copy(inname,outname)

In [ ]:
dfdata.loc[dfHY.index.tolist(),:].to_excel("to_HY_ORB_0915_bottom.xlsx")

In [ ]:
os.chdir(r"E:\20221011_figs\20221105 esr1 renew")

In [ ]:
dfnew = pd.read_excel("Esr1_POA_neurons_1105_chose.xlsx",index_col=0)

In [ ]:
dfnew.TH

In [ ]:
# top50 areas
dfnew.loc["sum"] =dfnew.apply(lambda x:x.sum(),axis =0)
dfnew = dfnew.sort_values(by = "sum",axis=1,ascending=False)
dfnew2 = dfnew.iloc[:,0:100]
df50  =dfnew2.drop(labels='sum',axis=0) 
df50.to_excel(os.path.join("All_neurons_1116_chose_top100.xlsx"))

In [ ]:
arealist = df50.columns.tolist()[0:50]

In [ ]:
arealist.append("MY")

In [ ]:
import pickle
with open("area_list.pkl","wb") as f:
    pickle.dump(arealist,f)

In [ ]:
df50.to_csv(os.path.join("Pdyn_VMH_neurons_neurons_1013_top50.csv"))

In [ ]:
areas51 = df50.columns.tolist()
areas51.append("ME")

In [ ]:
df51 = dfnew[areas51]

In [ ]:
df51.to_excel("all_neurons_0909_level8_top51.xlsx")

In [ ]:
dfarea = pd.read_excel("included_area_new.xlsx",index_col=0,header=None)

In [ ]:
arealist = dfarea.index.tolist()

In [ ]:
dfnew[arealist].to_csv("Hip_neurons_1004_level8_CTX_area.csv")

In [ ]:
map_list = []
for area in areas:
    if area in target:
        map_list.append(area)

In [ ]:
map_dic = {}
for area in map_list:
    father = dfmap.loc[dfmap.child == area].father.tolist()[0]
    if father not in map_dic:
        map_dic[father] = [area]
    else:
        map_dic[father].append(area)

In [ ]:
# 检查是否存在high-level 脑区已经存在的情况。
contain = []
for level,subarea in map_dic.items():
    contain.append(level in dfdata.columns.to_list())

In [ ]:
for level,subarea in map_dic.items():
    dfdata[level] = dfdata[subarea].apply(lambda x: x.sum(), axis=1)
    dfdata.drop(subarea,axis=1,inplace=True)

In [ ]:
dfcluster = pd.read_excel(r"all_neurons_max_cluster.xlsx")
dfcluster.loc[:, "file"] = dfcluster["file"].str.replace(".swc", "")
dflabel = dfcluster[["file","cluster"]].set_index("file")

In [ ]:
dfdata = pd.read_excel("all_neurons_0726_level9.xlsx",index_col=0)

In [ ]:
dfnew = pd.concat([dflabel,dfdata],axis=1)

In [ ]:
dfnew2 = dfnew.loc[dfnew.cluster >23]
dfnew2.to_excel("MY_neuron_level9.xlsx")

In [ ]:
dflabel = dfcluster[["file","cluster"]].set_index("file")

In [ ]:
import pandas as pd
from change_level import brain_level

In [ ]:
bl = brain_level()
bl.check_high_level_area(dfdata=dfdata,level=8)

In [ ]:
dfnew = bl.up_projection2level()

In [ ]:
dfnew

In [ ]:
def nor_level_7(x):
    # print(x["location"])
    if x["location"] in dfmap.child.tolist():
        return dfmap.loc[dfmap.child == x["location"]].father.tolist()[0]
    if x["location"] not in dfmap.child.tolist():
        return x["location"]

# 注意需要设置axis==1，这是series的index是columns
dfcluster.loc[:,"location2"] = dfcluster.apply(nor_level_7, axis=1)