In [7]:
import pandas as pd
import os

In [8]:
os.chdir(r"J:\beh\firbe photometry mice\calb1\20240226_combine_befsti")

In [10]:
df = pd.read_excel("20240228_Calb1_latency.xls",index_col=0)

In [20]:
df = pd.read_excel("20240226_Calb1_latency.xls",index_col=0)

In [11]:
df

,beh_bout,mouse,behavior,latency
filename,,,,
Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_fscope_1th_OVX_initial_align,Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_...,M11,initial,-1.28
Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_fscope_1th_OVX_socialnew_align,Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_...,M11,socialnew,-1.18
Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_fscope_1th_OVX_socialnew_align,Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_...,M11,socialnew,-0.28
Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_fscope_1th_OVX_socialnew_align,Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_...,M11,socialnew,-0.22
Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_fscope_1th_OVX_socialnew_align,Calb1_M11_20190604_mpoa_GCaMP6s_400nl_device1_...,M11,socialnew,-0.36
...,...,...,...,...
Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_fscope_2th_OVX_ejaculation_align,Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_...,M62,ejaculation,-1.64
Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_fscope_2th_OVX_initial_align,Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_...,M62,initial,0.34
Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_fscope_2th_OVX_intromit_align,Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_...,M62,intromit,-2.02
Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_fscope_2th_OVX_mount_align,Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_...,M62,mount,-0.68
Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_fscope_2th_OVX_smt_align,Calb1_M62_20200910_mpoa_GCamp6s_400nl_device1_...,M62,smt,-0.90

In [4]:
files = df.index.unique()

In [9]:
df.index.tolist()[0].split("_")[4]

'GCaMP6s'

In [12]:
df["virus"] = [item.split("_")[4] for item in df.index.tolist()]

In [13]:
df["mouse2"] = "Calb1_"+df["mouse"]

In [14]:
df.virus.value_counts()

GCaMP6s       635
FASGCaMP6s    623
GCamp6s       514
FASGCamp6s    138
Name: virus, dtype: int64

In [15]:
df.to_excel("20240228_Calb1_latency_new.xlsx")

In [14]:
df.virus.value_counts()

GCaMP6s       324
FASGCaMP6s    211
GFP           170
FASEYFP       156
GCamp6s       140
FASGCamp6s     81
Name: virus, dtype: int64

In [2]:
os.chdir(r"H:\20240124_MPOA_cluster_base\20240205_sort_heatmap")

In [3]:
df = pd.read_excel("MPO_cluster_9.xlsx",index_col=0)

In [7]:
df

                      cluster     neurons genotype location
file
180712_001_Esr1_MPN         3  180712_001     Esr1      MPN
180712_002_Esr1_MPN         3  180712_002     Esr1      MPN
180712_004_Esr1_MPN         4  180712_004     Esr1      MPN
180712_005_Esr1_MPN         1  180712_005     Esr1      MPN
180712_006_Esr1_VMPO        4  180712_006     Esr1     VMPO
...                       ...         ...      ...      ...
212202_037_Trh_MPN          3  212202_037      Trh      MPN
212202_044_Trh_MPN          5  212202_044      Trh      MPN
212202_051_Trh_LPO          3  212202_051      Trh      LPO
212202_060_Trh_HY           5  212202_060      Trh       HY
212202_061_Trh_HY           8  212202_061      Trh       HY

[1053 rows x 4 columns]

In [16]:
df2 = df.sort_values(by=["cluster","genotype"],ascending=True)

In [18]:
df2.to_csv("MPO_cluster_9_sort.csv")

In [12]:
df3 = df2.sort_values(by="genotype",ascending=True)

In [14]:
df4 = df3.sort_values(by="cluster",ascending=True)

In [15]:
df4

                     cluster     neurons genotype location
file
201924_144_Nts_LPO         1  201924_144      Nts      LPO
201226_018_Nts_AHN         1  201226_018      Nts      AHN
201228_058_Nts_BST         1  201228_058      Nts      BST
180715_005_Esr1_MPN        1  180715_005     Esr1      MPN
201224_074_Nts_MPO         1  201224_074      Nts      MPO
...                      ...         ...      ...      ...
201924_077_Nts_AHN         9  201924_077      Nts      AHN
201924_092_Nts_MPN         9  201924_092      Nts      MPN
201228_060_Nts_MPN         9  201228_060      Nts      MPN
201228_010_Nts_MPN         9  201228_010      Nts      MPN
180712_036_Esr1_MPN        9  180712_036     Esr1      MPN

[1053 rows x 4 columns]

In [3]:
df = pd.read_excel("cluster_MPO_male_4.xls")

In [8]:
dfdata = pd.read_excel("Esr1_soma_infor_0417_new.xlsx")

In [17]:
dfdata = dfdata.set_index("file")

In [13]:
df["new"] = ["180"+item[2:5]+"_"+item[5:8] for item in df["Unnamed: 0"].tolist()]

In [16]:
df = df.set_index("new")

In [22]:
dfall = pd.concat([df.cluster,dfdata],axis=1)

In [20]:
dfall = dfall.set_index("files")

In [26]:
dfall.to_excel("Esr1_soma_infor_0114_new.xlsx")

In [29]:
filename = os.listdir(r"H:\20240115_All_MPOA\swc_small")

In [31]:
filename2 = [item.split(".")[0] for item in filename]

In [34]:
os.chdir(r"H:\20240115_All_MPOA")

In [42]:
df = pd.read_excel("mPOA_neurons_0418_top50.xlsx",index_col=0)
dftmp = df.loc[df.index.isin(filename2)]
dftmp.to_excel("mPOA_neurons_0418_top50_small.xlsx")

In [3]:
os.chdir(r"H:\20240115_All_MPOA\20240418_pathways\combine_infor")

In [5]:
df1 = pd.read_csv("mPOA_projection_HY_types.csv",index_col=0)

In [9]:
df2 = pd.read_csv("mPOA_projection_out_HY_types.csv",index_col=0)

In [7]:
df2

,PAG,VTA\PRNr\ml,PB\MRN\PPN,PCG\CS,MY,PVT\MD\LH,MEA\CEA,MS\NDB\CA1,ACB\LS,type
180712_001_Esr1_MPN,0.191732,0.000000,0.062682,0.000000,0.000000,0.016986,0.000000,0.281717,0.178469,"PAG,PB\MRN\PPN,PVT\MD\LH,MS\NDB\CA1,ACB\LS"
180712_002_Esr1_MPN,0.390256,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007013,"PAG,ACB\LS"
180712_004_Esr1_MPN,0.000000,0.140069,0.559748,0.000000,0.000000,0.000000,0.098868,0.028024,0.000000,"VTA\PRNr\ml,PB\MRN\PPN,MEA\CEA,MS\NDB\CA1"
180712_005_Esr1_MPN,0.250304,0.187152,0.265058,0.000000,1.066061,0.000000,0.000000,0.000000,0.058252,"PAG,VTA\PRNr\ml,PB\MRN\PPN,MY,ACB\LS"
180712_006_Esr1_VMPO,0.329479,0.100319,0.035349,0.628807,0.000000,0.058669,0.000000,0.198088,0.029609,"PAG,VTA\PRNr\ml,PB\MRN\PPN,PCG\CS,PVT\MD\LH,MS..."
...,...,...,...,...,...,...,...,...,...,...
212202_037_Trh_MPN,0.144190,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012919,0.044833,"PAG,MS\NDB\CA1,ACB\LS"
212202_044_Trh_MPN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,no
212202_051_Trh_LPO,0.163619,0.000000,0.000000,0.031813,0.000000,0.000000,0.000000,0.000000,0.157397,"PAG,PCG\CS,ACB\LS"
212202_060_Trh_HY,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.584888,0.000000,0.259891,"MEA\CEA,ACB\LS"
212202_061_Trh_HY,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,no

In [10]:
df3 = pd.concat([df1.type,df2.type],axis=1)

In [12]:
df3.columns = ["In_HY","Out_HY"]

In [14]:
df3["geno"] = [item.split("_")[2] for item in df3.index.tolist()]

In [19]:
in_items = df3.In_HY.value_counts().index.tolist()[0:24]

In [21]:
out_items = df3.Out_HY.value_counts().index.tolist()[1:34]

In [24]:
df3.to_csv("all_neuron_Data.csv")

In [23]:
df4 = df3.loc[df3.In_HY.isin(in_items)&df3.Out_HY.isin(out_items)]

In [25]:
df4.to_csv("chose_MPOA_neuron_Data.csv")