In [2]:
import pandas as pd
import os
import numpy as np
import scipy.stats as stats
os.chdir(r"J:\BLA_three_types\dot")

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['pdf.fonttype'] = 42
mpl.rcParams['ps.fonttype'] = 42
plt.rc("font",family="Arial")

In [3]:
dft = pd.read_csv("bilateral_top65.csv",index_col=0)

In [8]:
dft = pd.read_excel("BLA_neurons_bilateral_all.xlsx",index_col=0)

In [11]:
dfc = pd.read_excel("BLA_3_cluster5.xlsx",index_col=0)

In [9]:
dft.columns = dft.columns.str.replace("_ipsi","")

In [13]:
dft = dft.loc[dfc.index.tolist()]

In [7]:
dfc = pd.read_csv("top60_cluster.csv",index_col=0)

In [14]:
dfp = pd.concat([dfc,dft],axis=1)

In [16]:
dfp.to_csv("all_axon_length_cluster.csv")

In [15]:
dfp

,cluster,int,PSV,PT,AAA,ACB,ADP,VL,nst,och,...,ENT_contra,GU_contra,AI_contra,BLA_contra,MOp_contra,PERI_contra,MOs_contra,SSs_contra,VISC_contra,EP_contra
251034_010_Vglut1,5,0.000000,0.000000,0.000000,0.000000,12177.902425,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_015_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221058_038_Sst,1,2880.183789,0.000000,0.000000,0.000000,75.257641,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221058_107_Sst,3,2.316553,0.000000,1006.996048,3954.466593,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221297_038_Sst,1,3168.466262,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_031_Crh,3,0.000000,0.000000,0.000000,109.023581,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
252460_132_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221058_040_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_016_Crh,1,5159.139265,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
242655_057_Sst,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_017_Crh,1,547.549178,0.000000,0.000000,2537.749124,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
251039_029_Vglut1,5,0.000000,0.000000,0.000000,325.194555,3485.504156,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
230058_076_Sst,1,4515.119669,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
230058_078_Sst,1,1085.176590,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
252459_079_Sst,2,182.393838,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
230058_074_Sst,1,3943.330547,0.000000,0.000000,0.000000,0.000000,0.000000,562.796214,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
251039_021_Vglut1,5,2207.850913,0.000000,0.000000,2237.098429,29715.687301,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
251034_001_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_020_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221058_071_Sst,2,0.000000,0.000000,0.000000,182.108881,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221297_036_Sst,1,891.791363,1138.221952,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221058_104_Sst,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
252459_074_Sst,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_019_Crh,3,0.000000,0.000000,0.000000,1318.511291,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221297_037_Sst,1,3293.659981,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
230058_073_Sst,2,1991.640033,0.000000,0.000000,0.000000,0.000000,0.000000,484.138439,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_122_Crh,3,0.000000,0.000000,0.000000,365.019920,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_086_Crh,3,0.000000,0.000000,0.000000,209.968306,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
251039_020_Vglut1,5,0.000000,0.000000,0.000000,118.199117,24251.948919,0.000000,269.755368,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
251039_033_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_021_Crh,3,0.000000,0.000000,0.000000,1340.251285,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
221058_088_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
251039_031_Vglut1,4,0.000000,0.000000,0.000000,0.000000,2729.331923,416.837433,0.000000,0.0,0.000000,...,0.00000,445.758462,97.776838,165.448553,2559.91932,0.00000,434.728329,2795.464027,589.441346,3065.887096
221058_113_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
251034_003_Vglut1,4,0.000000,0.000000,0.000000,0.000000,17372.033400,0.000000,0.000000,0.0,0.000000,...,4407.91756,79.866449,448.855893,0.000000,0.00000,98.55577,0.000000,235.324882,0.000000,2346.218196
251034_004_Vglut1,5,63.244120,0.000000,0.000000,0.000000,147.075428,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
234172_034_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000
251039_022_Vglut1,3,1456.034777,0.000000,0.000000,2544.371281,23742.288239,0.000000,0.000000,0.0,270.304466,...,0.00000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000

In [3]:
dfdata = dfc.loc[dfc.cluster>15]

In [7]:
dfdata.to_excel("midbrain_neurons_0920_chose_cluster.xlsx")

In [23]:
dfdata = pd.concat([dfc.cluster,dfp],axis=1)

In [24]:
dfdata.to_excel("Esr1_VMHvl_neurons_0719_chose_cluster.xlsx")

In [7]:
dfdata.to_excel("mPOA_neurons_0424_chose_cluster.xlsx")

In [15]:
os.chdir(r"H:\20230302_figs\20230306_VMH_all_marker_included\dotplot")

In [ ]:
# 0809 数据准备
df1 = pd.read_excel("all_soma_infor_MBO.xlsx",index_col=0)
df2 = pd.read_excel("infor_base_data_XXH.xlsx",index_col=0)
df2 = df2.set_index("name")
dfdata = pd.concat([df1.loaction2,df2],axis =1)

In [2]:
df200 = pd.read_excel("mPOA_neurons_0418_chose_cluster.xlsx",index_col =0)

In [3]:
df200 = pd.read_csv("Tu_Sst_projection_bilateral_all_cluster.csv",index_col=0)

In [10]:
df200 = df200.loc[df200.cluster >15]

In [3]:
df200 = pd.read_excel("two_compare.xlsx",index_col=0)

In [13]:
df200 = pd.read_csv("PL_to_HY_all_chose.csv",index_col=0)

In [35]:
dfdata = pd.read_excel("Esr1_VMHvl_neurons_0719_chose_cluster.xlsx",index_col=0)

In [11]:
df200 = dfp

In [39]:
# location base
def get_wendu_type(x):
    return x.p*len(df)/(x.name+1)

dfall = pd.DataFrame()
dftmp = pd.DataFrame()
for i in set(df200.cluster.to_list()):
    dfin = df200.loc[df200.cluster ==i]
    dfout = df200.loc[df200.cluster !=i]
    sumab = len(dfin)
    sumcd = len(dfout)
    dict_tmp = {}
    for area in df200.columns.tolist():
        if area != "cluster":
            a = (dfin[area]>0).astype("int").sum()
            b = sumab - a
            c = (dfout[area]>0).astype("int").sum()
            d = sumcd -c
            obs2 = [[a,b], [c,d]]
            ratio, pvalue =stats.fisher_exact(obs2)
            if ratio >1:
                dict_tmp[area] = pvalue
        dic_total = {}
        area_tmp = "cluster_%s"%(i)
        dic_total[area_tmp] = dict_tmp
        df = pd.DataFrame(dic_total)
        try:
            df.loc[:,"cluster"] = i
            df.columns = ["p","cluster"]
            df = df.sort_values(by = "p",axis=0,ascending=True)
            df = df.reset_index(drop=False)
            df.columns = ["area","p","cluster"]
            df.loc[:, "FDR"] = df.apply(get_wendu_type, axis=1)
            dftmp = df.iloc[0:30,:]
            # dftmp = df.iloc[0:20,:]
        except:
            pass
    dfall = pd.concat([dfall,dftmp],axis=0)

In [41]:
dfall.loc[dfall.cluster ==5]

    area             p  cluster       FDR
0    ORB  6.339016e-07        5  0.000039
1    MOs  1.727382e-05        5  0.000535
2     PL  1.727382e-05        5  0.000357
3    OLF  6.275625e-05        5  0.000973
4    AON  1.958756e-04        5  0.002429
5    ACA  2.383470e-04        5  0.002463
6    FRP  2.383470e-04        5  0.002111
7    ILA  4.741584e-04        5  0.003675
8     OT  7.910299e-04        5  0.005449
9     EP  9.064792e-04        5  0.005620
10    CP  2.521660e-03        5  0.014213
11    fa  4.148886e-03        5  0.021436
12   ACB  4.249359e-03        5  0.020266
13    AI  6.133632e-03        5  0.027163
14    MA  1.325710e-02        5  0.054796
15   ccb  1.517307e-02        5  0.058796
16  scwm  1.517307e-02        5  0.055337
17    DP  1.517307e-02        5  0.052263
18   ccg  2.987198e-02        5  0.097477
19  ProS  2.987198e-02        5  0.092603
20   alv  2.987198e-02        5  0.088193
21   AUD  2.987198e-02        5  0.084185
22   CA1  2.987198e-02        5  0.080524
23  cing  2.987198e-02        5  0.077169
24  PERI  2.987198e-02        5  0.074083
25    FS  3.412894e-02        5  0.081384
26   amc  3.412894e-02        5  0.078370
27    SI  3.412894e-02        5  0.075571
28    TT  3.462751e-02        5  0.074031
29   PIR  4.073071e-02        5  0.084177

In [42]:
dfall = dfall.loc[dfall.p<0.05]

In [43]:
dfall

            area             p  cluster           FDR
0             PB  6.134531e-09        1  4.907625e-07
1              P  6.134531e-09        1  2.453813e-07
2            PPN  6.134531e-09        1  1.635875e-07
3            scp  1.840359e-07        1  3.680719e-06
4   fiber tracts  1.349597e-06        1  2.159355e-05
..           ...           ...      ...           ...
25            FS  3.412894e-02        5  8.138440e-02
26           amc  3.412894e-02        5  7.837017e-02
27            SI  3.412894e-02        5  7.557123e-02
28            TT  3.462751e-02        5  7.403122e-02
29           PIR  4.073071e-02        5  8.417680e-02

[76 rows x 4 columns]

In [16]:
dfall.to_csv("20_marker_region_type_diff.csv")

In [44]:
listold = dfall.area.tolist()
listshort = ["cluster"]
for itm in listold:
    if itm not in listshort:
        listshort.append(itm)

df200[listshort].to_excel("BLA_3_type_diff_projection_raw.xlsx")

In [46]:
df200[["ec"]]

                            ec
251034_010_Vglut1   292.396439
234172_015_Crh      348.822705
221058_038_Sst     1823.797246
221058_107_Sst      189.738140
221297_038_Sst      354.435529
234172_031_Crh        0.000000
252460_132_Sst      647.886628
221058_040_Sst       73.350442
234172_016_Crh        0.000000
242655_057_Sst      492.221095
234172_017_Crh        0.000000
251039_029_Vglut1  1002.314866
230058_076_Sst      290.503353
230058_078_Sst      158.633460
252459_079_Sst       85.069604
230058_074_Sst      614.959900
251039_021_Vglut1   352.075665
251034_001_Vglut1   209.065574
234172_020_Crh        0.000000
221058_071_Sst       43.983704
221297_036_Sst      164.683689
221058_104_Sst        0.000000
252459_074_Sst      444.590567
234172_019_Crh       12.754498
221297_037_Sst      367.041545
230058_073_Sst      430.305682
234172_122_Crh      859.866651
234172_086_Crh        0.000000
251039_020_Vglut1   894.579095
251039_033_Vglut1   859.369376
234172_021_Crh        0.000000
221058_088_Sst       97.232406
251039_031_Vglut1   847.655659
221058_113_Sst        0.000000
251034_003_Vglut1   377.918760
251034_004_Vglut1   534.598838
234172_034_Crh        0.000000
251039_022_Vglut1     0.000000

In [45]:
df200[listshort]

,cluster,PB,P,PPN,scp,fiber tracts,MB,SNr,arb,MRN,...,alv,AUD,CA1,cing,PERI,FS,amc,SI,TT,PIR
251034_010_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,684.800576,0.000000,4183.218033,923.534321,0.000000
234172_015_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221058_038_Sst,1,5467.253998,67.438845,1407.142434,17.276158,1283.236618,1179.102777,1472.773986,282.038560,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1164.516310,3576.375407,0.000000,697.150374
221058_107_Sst,3,0.000000,0.000000,0.000000,0.000000,2564.518920,235.706206,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,73.361376,0.000000,2422.323391,0.000000,0.000000
221297_038_Sst,1,11327.702579,73.753485,241.650666,2321.822688,145.654832,1371.191756,152.034788,2332.098550,1754.516187,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_031_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
252460_132_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,79.299520,0.000000,0.000000,0.000000
221058_040_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,22.442790,0.000000,0.000000,2531.731684
234172_016_Crh,1,1026.462770,223.720779,6982.473195,194.845534,142.847321,8150.304820,2450.373311,0.000000,408.815146,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
242655_057_Sst,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,379.880565,0.000000,0.000000,0.000000
234172_017_Crh,1,1424.404948,1032.346785,2009.536150,241.812244,91.604157,1687.826768,1107.522746,0.000000,7.730143,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4546.972781,0.000000,0.000000
251039_029_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,752.182567,0.000000,312.602719,0.000000,951.466253,336.639264,1343.312145,0.000000,4124.555190
230058_076_Sst,1,5316.098383,80.752699,1132.153196,1897.946918,737.990692,831.111426,1623.841404,665.193607,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
230058_078_Sst,1,8301.003362,1043.160899,988.035244,2233.091312,2907.341760,2635.520649,1505.000243,2245.344050,1440.578814,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
252459_079_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
230058_074_Sst,1,13723.567119,366.914135,599.752505,1596.638855,684.341280,1145.931138,1019.084106,3501.431867,169.250479,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
251039_021_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,64.169071,748.657473,8133.585429,0.000000,17.602532,318.845964,121.544374,5551.559822,2850.455413,0.000000
251034_001_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,103.525133,0.000000,0.000000,7344.576837
234172_020_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221058_071_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,777.365310,0.000000,0.000000,9661.775558
221297_036_Sst,1,4692.066585,275.346647,1055.607813,0.000000,163.826107,166.765490,0.000000,691.263665,1984.099038,...,0.000000,0.000000,0.000000,0.000000,0.000000,136.112345,0.000000,0.000000,0.000000,0.000000
221058_104_Sst,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
252459_074_Sst,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_019_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
221297_037_Sst,1,8535.301463,996.146837,1062.774836,1236.655597,212.799799,0.000000,0.000000,343.582301,1778.171158,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
230058_073_Sst,2,0.000000,0.000000,0.000000,0.000000,209.218895,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
234172_122_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,99.554121,0.000000,2930.473830,0.000000,0.000000
234172_086_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,275.450234,0.000000,42.897112,0.000000,0.000000
251039_020_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,625.145060,0.000000,9434.777242,0.000000,0.000000,1320.274312,0.000000,2857.748016,336.584238,0.000000
251039_033_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,168.324861,0.000000,704.610486,0.000000,0.000000,1646.657005
234172_021_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,23.158051,0.000000,0.000000,0.000000,0.000000
221058_088_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
251039_031_Vglut1,4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1102.301245,517.620126,498.926171,0.000000,4835.756914
221058_113_Sst,2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
251034_003_Vglut1,4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1324.069730,380.965571,10291.543408,3010.408816,762.307708
251034_004_Vglut1,5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,94.264511,0.000000,75.923179,54.638765,1050.993903,0.000000,86.546279
234172_034_Crh,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
251039_022_Vglut1,3,0.000000,0.000000,0.000000,0.000000,122.307305,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1819.840468,114.013661,11892.345624,1054.661734,0.000000

In [9]:
dfall.to_csv("5_marker_region.csv")

In [12]:
def get_wendu_type(x):
    return x.p*len(df)/(x.name+1)

dfall = pd.DataFrame()
for i in set(df200.cluster.to_list()):
    dfin = df200.loc[df200.cluster ==i]
    dfout = df200.loc[df200.cluster !=i]
    sumab = len(dfin)
    sumcd = len(dfout)
    dict_tmp = {}
    for area in df200.columns.tolist():
        if area != "cluster":
            a = (dfin[area]>0).astype("int").sum()
            b = sumab - a
            c = (dfout[area]>0).astype("int").sum()
            d = sumcd -c
            obs2 = [[a,b], [c,d]]
            ratio, pvalue =stats.fisher_exact(obs2)
            if ratio >1:
                dict_tmp[area] = pvalue
        dic_total = {}
        area_tmp = "cluster_%d"%(i)
        dic_total[area_tmp] = dict_tmp
        df = pd.DataFrame(dic_total)
        try:
            df.loc[:,"cluster"] = i
            df.columns = ["p","cluster"]
            df = df.sort_values(by = "p",axis=0,ascending=True)
            df = df.reset_index(drop=False)
            df.columns = ["area","p","cluster"]
            df.loc[:, "FDR"] = df.apply(get_wendu_type, axis=1)
            # dftmp = df.iloc[0:10,:]
            dftmp = df.iloc[0:5,:]
        except:
            pass
    dfall = pd.concat([dfall,dftmp],axis=0)

In [1]:
dfall

NameError: name 'dfall' is not defined

In [19]:
dfall.loc[dfall.area == "BST",:]

   area             p cluster           FDR
33  BST  7.329698e-15     MPO  3.513944e-14

In [ ]:
['MO','SS','FRP','GU','AI','ECT','PERI','VIS','ILA','ACA','PL']

In [18]:
dfp.to_excel("PAG_enrich_p_samll_5.xlsx")

In [17]:
dfp = dfall.loc[dfall.p <0.05]

In [22]:
dfall.to_excel("enrich.xlsx")

In [23]:
dfall.to_excel("differernt areas_PL2HY.xlsx")

In [20]:
dfall = pd.read_excel("module_enrich_areas.xlsx",index_col=0)

In [ ]:
listold = dfall.area.tolist()
listshort = ["cluster"]
for itm in listold:
    if itm not in listshort:
        listshort.append(itm)

df200[listshort].to_excel("Tu_Sst_projection_enrich_bilateral_raw.xlsx")

In [11]:
df200[listshort].to_excel("Tu_Sst_projection_enrich_bilateral_raw.xlsx")

In [10]:
%reset

In [16]:
df200[listshort]

,cluster,MY,PGRNl,SOC,LRNm,IRN,MDRNd,PARN,NTS,MO,...,MPN,CEA,LS,MPO,LPO,AVP,IPN,PPN,SI,scp
192710_003_Pomc_TU,29,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,981.149048,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
192710_010_Pomc_TU,25,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,374.083252,0.000000,0.000000,1603.174316,527.710083,0.0,0.0,0.000000,1182.596558,0.000000
192710_012_Pomc_HY,23,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,387.822205,0.000000,0.000000,0.000000,0.0,0.0,998.092651,987.371216,275.690857
192710_017_Pomc_HY,25,23.608397,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,1712.728638,790.904907,546.652954
192710_020_Pomc_HY,29,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,2124.036621,134.131180,6315.397949,241.082367,0.000000,0.0,0.0,892.518494,799.764709,255.942337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220102_116_Crh_HY,31,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,778.411194,0.000000,585.584167,0.000000,0.0,0.0,0.000000,2372.367432,0.000000
220102_119_Crh_PVHd,26,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,502.715240,0.000000,0.0,0.0,0.000000,0.000000,0.000000
220102_121_Crh_PVH,20,1316.794922,310.620514,915.68512,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000
220102_139_Crh_DMH,25,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,3272.485107,0.000000,0.000000,252.140671,0.0,0.0,3770.289551,0.000000,152.735992
220102_149_Crh_DMH,23,0.000000,0.000000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,543.917114,0.000000,0.000000

In [11]:
df200.to_excel("VMHdm_pdyn_data.xlsx")

In [ ]:
dfnew[list(set(listnew))].to_excel("orexin_enrich_area.xlsx")

In [ ]:
dfnew[listnew].to_excel("orexin_enrich_area_projection.xlsx")

In [ ]:
set(listnew)

In [ ]:
loclist = []
for area in dfall.area.tolist():
    if area not in loclist:
        loclist.append(area)

In [ ]:
loclist.append("cluster")

In [ ]:
dfarea = df200[loclist]

In [ ]:
dfarea.to_excel("MY_enrich_cluster.xlsx")

In [ ]:

df3 = df2.loc[df2.cluster <12]
dfplot = pd.concat([df3[["cluster","neurons"]].set_index("neurons"),df200[loclist]],axis =1)

In [ ]:
dfnew = pd.pivot_table(dfplot,index="cluster",aggfunc="mean",fill_value=0)

In [ ]:
dfplot2 = dfnew[loclist].stack().unstack(0)

In [ ]:
dfplot2 = dfnew[loclist]

In [ ]:
dfall = pd.read_excel("projection_cluster.xlsx",index_col=0)

In [ ]:
dfarea = pd.read_excel("differernt areas_MY.xlsx",index_col=0)

In [ ]:
dfplot = dfdata.loc[dfdata.cluster >23]

In [ ]:
dfplot

In [ ]:
for i in set(dfarea.cluster.tolist()):
    plotlist = dfarea.loc[dfarea.cluster==i].area.tolist()
    plotlist.append("cluster")
    dfplot2 = dfplot[plotlist]
    dfnew = pd.pivot_table(dfplot2,index="cluster",aggfunc="mean",fill_value=0)
    fig, ax = plt.subplots(figsize = (4.5,4))
    # sns.set(font_scale=1.9)
    sns.heatmap(data = dfnew,cmap="YlGnBu",vmin=0,
                    vmax=2000)
    plt.savefig("heatmap_for_marker region_%d.jpg"%(i),dpi =600)
    plt.savefig("heatmap_for_marker region_%d.pdf"%(i),dpi =600,format="pdf")
    plt.close()

In [ ]:
# for HY
areaplot = {"moldue1":["MEA","CEAm","BMAa","BMAp","PA","COAp","CA","fi"],
"moldue2":["LH","MD","PVT","PRC","PAG"],
"moldue3":["BST","LPO","MPO","MPN","LSv","LSr"],
"moldue4":["VMH","DMH","PMv"],
"moldue5":["ARH","TU","LHA","VMH","ME"],
"moldue6":["AM","PR","VM","SMT"]
}

In [ ]:
for area in areaplot:

    plotlist = areaplot[area]
    plotlist.append("cluster")
    dfplot2 = dfplot[plotlist]
    dfnew = pd.pivot_table(dfplot2,index="cluster",aggfunc="mean",fill_value=0)
    fig, ax = plt.subplots(figsize = (4.5,4))
    # sns.set(font_scale=1.9)
    sns.heatmap(data = dfnew,cmap="YlGnBu",vmin=0,
                    vmax=2000)
    plt.savefig("heatmap_for_marker region_%s.jpg"%(area),dpi =600)
    plt.savefig("heatmap_for_marker region_%s.pdf"%(area),dpi =600,format="pdf")
    plt.close()

In [ ]:
fig, ax = plt.subplots(figsize = (30,4))
# sns.set(font_scale=1.9)
sns.heatmap(data = dfplot2,cmap="YlGnBu",vmin=0,
                 vmax=2000)
plt.savefig("heatmap_for_marker region.jpg",dpi =600)
plt.savefig("heatmap_for_marker region.pdf",dpi =600,format="pdf")

In [ ]:
def get_wendu_type(x):
    return x.p/len(df)*(x.name+1)
df.loc[:, "FDR"] = df.apply(get_wendu_type, axis=1)

In [ ]:
df.top(10)

In [ ]:
(dfin.LHA>0).astype("int").sum()

In [ ]:
(dfout.LHA>0).astype("int").sum()

In [ ]:
import scipy.stats as stats

obs2 = [[10,3], [1,7]]

aa, bb=stats.fisher_exact(obs2)

print(aa)

In [ ]:
dfHY.loc[:,dfHY.loc["sum",:]>10000]

In [ ]:
(dfHY.amc>0).astype("int").sum()

In [ ]:
def get_wendu_type(x):
        aa = x.file
        return aa.split(".")[0]

# 注意需要设置axis==1，这是series的index是columns
df2.loc[:, "neurons"] = df2.apply(get_wendu_type, axis=1)

In [ ]:
df2[["cluster","neurons"]].set_index("neurons")